### ISSUE TITLE
Support clip-path for is-visible

### ISSUE THREAD

**Issue by AutoSponge** [dequelabs/axe-core#1001]
Desired behavior:
- axe identifies elements as visually hidden when CSS clip-path rules apply (e.g., `clip-path: inset(50%);`).

Challenge:
- several combinations of shape and param can "hide" an element. axe may need to simplify the check to a minimum of combinations (i.e., `inset >= 50` and `circle === 0`).

Current behavior:
- axe does not consider clip-path but does consider the deprecated `clip` rule.

See example:
- https://codepen.io/AutoSponge/pen/qyBxZr

**Comment by WilcoFiers** [comment]
Can you include an example, such as through code pen, showing the issue?

**Comment by jkodu** [comment]
Note:

Upon initial investigation, browser support is fairly limited to modern browsers for both `clip-path` and perhaps usage of `IntersectionObserver` to aid this computation.

**Comment by straker** [comment]
This my prove more difficult than we want. 

First `clip-path` isn't supported in Safari and Edge so it's based on the browser. 

Second, because the `clip-path` can take position properties, we'd have to know the dimensions of the area being clipped and determine if the clip-path is outside of that region. So for example, a 100x100 region would be hidden by this: `clip-path: circle(100% at 300px 300px);` but if the region was 600x600 it would not be. Getting the bounding rects of the region is probably not something we want to do in the `isVisible` check.

**Comment by AutoSponge** [comment]
I agree, it's difficult which is why we use code that looks for a common "hiding" pattern in axe-pro:

```js
  if (clipPath) {
    // not an exhaustive list but common for hiding on purpose
    const [, type, n] = clipPath.match(/(\w+)\((\d+)/) || [
      null,
      '',
      0
    ]
    switch (type) {
      case 'inset':
        return n >= 50
      case 'circle':
        return n === 0
      default:
    }
  }
```

**Comment by jeankaplansky** [comment]
@straker: What documentation is required with this in axe rule help if any? Or is it primarily new functionality to replace deprecated functionality? ("axe does not consider clip-path but does consider the deprecated clip rule." from https://github.com/dequelabs/axe-core/issues/1001)? Pls advise.

Thanks!

**Comment by straker** [comment]
I don't think any docs are required.

**Comment by jeankaplansky** [comment]
Cool. Moving on to QA then.

**Comment by somaalapati** [comment]
@straker I didn't get clarity on this issue after reading all comments. Please provide more details on how to test this fix?
