### ISSUE TITLE
Hyperlinks with missing href

### ISSUE THREAD

**Issue by ackleyk** [dequelabs/axe-core#1039]
- Link to live demo:

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by ackleyk** [comment]
Would it be possible for axe-core to flag hyperlinks with missing href attributes? 

I see this issue all the time when I'm keyboard testing; it seems like this might be an easy upgrade for a future version of axe-core.

Thank you!

**Comment by marcysutton** [comment]
Hyperlinks without href attributes are still valid HTML, so I don't think we can safely flag them without a false positive. @WilcoFiers what do you think?

**Comment by ackleyk** [comment]
@marcysutton , thank you for the quick response. If @WilcoFiers agrees with you, I will close the issue.

**Comment by WilcoFiers** [comment]
Yeah. Marcy's right. This is frequently used to put anchor points into a page that you can link to. I'm guessing you're looking more for `a` elements with event handlers attached to them? Those can be problematic as they're not focusable. They are a little harder to test with axe-core because there's no DOM API to identify what event handlers are on a page. We've got some ideas on how to approach this, but we couldn't do it the way you suggest as it would give false positives. Either way, thanks for the suggestion! Still much appreciated!

**Comment by ackleyk** [comment]
Great, thank you both for you feedback!
