### ISSUE TITLE
raw reporter shouldn't output DqElements

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1195]
While working on a new reporter I tried to run `JSON.stringify()` on the results of the `raw` reporter. Turns out that this is outputting DqElements, which can't be stringified after completing a run. Because the selectors are lazily constructed, and in order to construct them `axe._selectorData` is required, they can't be constructed after cleanup of `axe._selectorData`. To fix this we need to change the `raw` reporter to not output DqElement objects.

**Comment by jkodu** [comment]
Note:
Go thru results and any Dq element, toJson() or equivalent for selector

**Comment by jkodu** [comment]
@WilcoFiers - I was unable to find any DqElement in the raw report, so I could run a `toJson` on the same. Need more input.

**Comment by dbjorge** [comment]
We just hit this issue during development of https://github.com/Microsoft/axe-sarif-converter - the problematic elements are at JSON paths along the lines of `root_raw_results[0].violations[0].node` and `root_raw_results[0].violations[0].any[0].relatedNodes[0]`.

One option for a low-churn fix that we tried out successfully would be updating the raw reporter to output `JSON.parse(JSON.stringify(results))`, rather than outputting results directly. I don't know that I'd recommend this, though, since DqElement.toJSON omits some properties from the original DqElement; I think it would be preferable for the output of the raw reporter to be as close as possible to the input that a new reporter library would be receiving (using the output of the raw reporter as test cases for the new reporter we're developing has been our primary use case for the raw reporter so far), so I think it might be better to do a more explicit step to replace the lazy properties in question with non-lazy ones in the existing finalization phase before the results get passed to reporters (https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/finalize-result.js).

**Comment by AutoSponge** [comment]
@WilcoFiers so, the test at https://github.com/dequelabs/axe-core/blame/320e63380189f507a32c99fd19619f3c6a161764/test/core/utils/dq-element.js#L35 is not a valid test for your case?

That may defeat the purpose of the `raw` reporter. Could I suggest a `string` reporter that uses a `JSON.stringify({}, `**replacer**`)` function to remove or otherwise normalize DQElements?
