### ISSUE TITLE
axe-coconut does not recognize role="tree" and role="treeitem".

### ISSUE THREAD

**Issue by dervism** [dequelabs/axe-core#1222]
axe-coconut does not recognize role="tree" and role="treeitem". Our website contains a tree structure (ul & li's) that has sub-level nested groups that can be collapsed and expanded (see the link below). When validated with axe-coconut plugin in Chrome, the plugin reports violations:

```
<li> elements must be contained in a <ul> or <ol>
````

and 

```
List item does not have a <ul>, <ol> or role="list" parent element.
```

axe reports this violation for each of the treeitems when the sub-level groups are expanded (giving up 40 violations).

As far as I can read about _role=list_ and _role=tree_, the correct aria role in our case is a tree structure. The should in this case identify the tree role validate it as valid.

W3C docs:
https://www.w3.org/TR/wai-aria/#tree
https://www.w3.org/TR/wai-aria/#treeitem

- Link to live demo:
http://design.nav.no/#/components

<pre><code>
axe-Coconut: 3.5.0.28411 build 1e5ad27c18
axe-core version: 3.1.2
axe-devtools:3.5.0

Browser and Assistive Technology versions
Chrome v70

For Tooling issues:
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment]
Thank you for reporting. Axe-core does use tree / treeitem, but only if you use them as in a direct parent child relationship:

This:
```
<ul role="tree">
  <li role="treeitem">...</li>
</ul>
```

Instead of this:

```html
<ul role="tree">
  <li><a href="" role="treeitem">...</a></li>
</ul>
```

This is very much intentional. While in Chrome the second solution works, in Firefox it does not. We're actually in the process of researching a related issue (#1171). I'd like axe-core to be better able to report the problem, but in order to do so we'll need to understand it better first.

I'm closing this ticket, as it's largely a duplicate. Thank you again for reporting. I hope this response is helpful to you.
