### ISSUE TITLE
[3.2.0] Cannot find module './lib/axios'

### ISSUE THREAD

**Issue by wKovacs64** [dequelabs/axe-core#1405]
Attempts to update `axe-core` from 3.1.2 to 3.2.0 are causing Cypress tests to fail. From the error message, it looks like it can't resolve `axios` anymore? 

Expectation: no errors

Actual: `Error: Cannot find module './lib/axios' from '/root/project/node_modules/axe-core'`

Motivation: N/A

<pre><code>
axe-core version: 3.2.0
axe-webdriver, extension or other integration version: N/A

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 10  
- Platform: all 
</code></pre>

Here's a reproduction using `create-react-app` and Cypress (test copied from #755):

https://github.com/wKovacs64/cypress-axe-core-320

(Run `yarn cy:run` to start Cypress in headless mode in your CLI or `yarn cy:open` to launch the GUI.)

Thanks.

**Comment by WilcoFiers** [comment]
Thank you for reporting. Looking into it now.

**Comment by WilcoFiers** [comment]
@wKovacs64 @beardedtim looks like this problem is coming form Cypress being unexpectedly aggressive in overloading any variable called `require`. Axe-core uses an internal `require` to load its embedded dependencies.

A simple workaround I found is to use axe.min.js instead of axe.js. You can require it from `axe-core/axe.min.js`.

I'll put together a fix for this. Shouldn't be too difficult, just have to rename that `require` function.

**Comment by wKovacs64** [comment]
Thanks @WilcoFiers & crew!
