### ISSUE TITLE
role="none presentation" should not be a violation

### ISSUE THREAD

**Issue by salfej** [dequelabs/axe-core#1462]
See on-going discussion: https://github.com/bootstrap-vue/bootstrap-vue/issues/2921

**Expectation:** According to WAI-ARIA rules, there is not sufficient support for `role="none"`, and developers are encouraged to use `role="none presentation"`
https://www.w3.org/TR/wai-aria-1.1/#none
I wouldn't expect this to throw an error since it is conforming to standards.

**Actual:** This convention is categorized as a violation with a critical impact.
![image](https://user-images.githubusercontent.com/10404888/55027665-cdbe3800-4fd3-11e9-89f3-429e748041be.png)

**Motivation:** This could be categorized under the "Needs review" section as it does still adhere to WAI-ARIA 1.1 standards.

axe Chrome extension version: 3.8.0

**Comment by WilcoFiers** [comment]
@salfej Thank you for reporting. This is intentional behaviour. The problem is that fallback roles aren't supported in either IE or Edge (at least, not last time I checked). Instead what happens is that a role attribute with two values is ignored entirely. Axe-core has an assistive technology baseline documented here:
https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md

Basically, if a solution doesn't work in some of these assistive technologies we'll call it out as a problem in axe-core. Unfortunately, when it comes to WAI-ARIA following the spec often doesn't mean the code will work as expected. Axe-core calls these things out when we believe this can be done without false positives. Granted, axe-core can do a better job of reporting that fallback roles aren't widely supported. Solving this is on our roadmap already.

The upside of it is that you can easily improve this by simply doing `role="presentation"`. This will work much more reliably.

**Comment by tmorehouse** [comment]
`role="presentation"` can actually hide nested content that has an implied role (such as a link), or an action role with some screen readers, as they interpreted the spec wrong (equating `role="presentation"` with `"aria-hidden="true"`).

**Comment by salfej** [comment]
Ahh, I see. That makes sense from a coverage perspective. I didn't know IE and Edge wouldn't allow fallback roles. Good to hear reporting that kind of feedback to users is in the pipeline. Thanks!
