### ISSUE TITLE
False Lighthouse Error: Document doesn't have a <title> element

### ISSUE THREAD

**Issue by NithinGCC** [dequelabs/axe-core#1497]
Hi,
For one of our pages https://www.blinds.com/p/blindscom-2-deluxe-wood-blind/503440 we are seeing that the lighthouse is having issues with accessibility and SEO.
![image](https://user-images.githubusercontent.com/43421891/56155416-71ba5400-5f80-11e9-88f9-54143104054e.png)

"Document doesn't have a <title> element" error is shown but we do have the title tag in the DOM. Also, other SEO tools are seeing the page and tags properly. 
I read in some other threads about a possible Lighthouse-axe integration issue. I ran axe extension audit and I got this
![image](https://user-images.githubusercontent.com/43421891/56155617-fd33e500-5f80-11e9-9d2a-753b72a2a022.png)

Would you be able to help me here please?

Thanks,
Nithin

**Comment by patrickhulce** [comment]
To add a little more info here, Lighthouse fails because axe takes ~2 minutes to complete and our deadline is 60 seconds.

Most of this time seems to be spent in findDomNode

![image](https://user-images.githubusercontent.com/2301202/56157826-2145f500-5f86-11e9-8330-e1a006a176c6.png)

**Comment by straker** [comment]
Thanks for the issue. `isAccessibleRef` has been a performance bottleneck and contributes to some of the [slow rules](1464) that cause axe to take so long to complete. I've been looking at axe's performance over the past couple of weeks and hopefully will be able to start making great improvements for large pages.

**Comment by straker** [comment]
@patrickhulce Could you elaborate more on the 60s deadline for Lighthouse? Is that 60s for the entire run (including axe) or for each individual aspect Lighthouse tests (perf, a11y, etc.)? Do you have pages you run your benchmarks against that we could maybe test against against as well?

**Comment by patrickhulce** [comment]
It's 60 seconds for each "gatherer" which is for each script we run on the page. Axe is one such script and so if axe does not complete within 60 seconds, all accessibility audits will display an error in the report.

We don't have the extremely large sites that axe typically fails on in our regular test suite (most of those come from end-user reports), but https://github.com/GoogleChrome/lighthouse/issues/2293 is an older issue that tracked a set of sites that were particularly slow. A few of those might still be good axe candidates? It's tricky because in many cases what slows axe down also slows the page itself down and so it tends to get fixed by the site owner at some point :)

**Comment by molant** [comment]
One of my to-go sites to stress tools is www.tmz.com. Might be worth giving it a try.

**Comment by straker** [comment]
Thanks for the information. I'll take a look at the sites.

**Comment by straker** [comment]
I'm going to close this issue for now. With the latest perf changes, axe runs in under 10s on the given page. I'll continue to work on improving axe's performance.
