### ISSUE TITLE
merge multiple `isHidden` utility functions

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core#1519]
We have multiple fn's that do more or less the same thing:
- `dom.isVisible`
- `util.isHidden`
- `dom.isHiddenWithCss`

Nice to have:
- It would be nice to merge these with optional arguments perhaps

Good to solve:
- see https://github.com/dequelabs/axe-core/pull/1503#discussion_r278557709

Must do:
- decorate `@deprecated` if we choose to not use any.

**Comment by straker** [comment]
Here's my findings in comparing the 3 functions

|                                     | `utils/is-hidden` | `dom/is-visible` | `dom/is-hidden-with-css` |
| --------------------- | ---------------- | ---------------- | -------------------------- |
| takes single element |  ✓ Yes | ✓ Yes | ✓ Yes |
| takes `screenReader` option | × No | ✓ Yes | × No |
| looks at `nodeType` |  ✓ Yes | ✓ Yes | ✓ Yes |
| looks at `nodeName` | × No | ✓ Yes | ✓ Yes |
| looks at css `display` |  ✓ Yes | ✓ Yes | ✓ Yes |
| looks at css `visibility` |  ✓ Yes | ✓ Yes | ✓ Yes |
| looks at `aria-hidden` |  ✓ Yes | ✓ Yes | × No | 
| looks at css `clip` | × No | ✓ Yes | × No |
| looks at css `opacity` | × No | ✓ Yes | × No |
| looks at css scroll height | × No | ✓ Yes | × No |
| looks at offscreen | × No | ✓ Yes | × No |
| recurses with parent el |  ✓ Yes | ✓ Yes | ✓ Yes | 

And how they are used in the code:

- `utils/is-hidden`
  - when gathering nodes in `core/rule.js` gather step
  - when gathering frames in `core/context.js`
- `dom/is-hidden-with-css` 
  - checking if element is hidden in `dom/focus-disabled.js`
  - checking if form control is hidden in `text/form-control-value.js`
- `dom/is-visible`
   - everywhere else

`utils/is-hidden` is used only in the two files to gather nodes before passing them to a rule/check, and `dom/is-hidden-with-css`  is used in two specific files, though I'm not sure why it is used over `dom/is-visible`. `dom/is-visible` is used the majority of the time (59 matches when doing a search) and is the function other code bases use to check an elements visibility. 

Therefore, I propose we deprecate `utils/is-hidden` and `dom/is-hidden-with-css` and use `dom/is-visible` as the single function. Since we need the function in `core`, we can move the function to `utils` and export it in `dom` like we've done for functions (making it backwards compatible).

**Comment by straker** [comment]
@WilcoFiers suggest mimicking ACT definitions of `is-visible` and `is-hidden-state` which help distinguish when a DOM node is visually visible (offscreen, visible, etc., excluding aria-hidden) and when a node is hidden from the accessibility tree (looks at aria-hidden, visibility, and display)

**Comment by WilcoFiers** [comment]
I don't see us ever making this change. I don't think the effort out weights the effort involved in making this change.
