### ISSUE TITLE
Autocomplete Check confusing

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#1561]
```<input type="tel" name="credit-card-number" placeholder="" aria-placeholder="" inputmode="numeric" autocorrect="off" autocapitalize="none" spellcheck="false" autocomplete="cc-number" autocompletetype="cc-number" x-autocompletetype="cc-number" maxlength="22" aria-invalid="false">```
 
not sure why this is failing
Ensure the autocomplete attribute is correct and suitable for the form field
Issue tags:
category: forms
wcag21aa
wcag135

Maybe it is because there is x-autocompletetype?

**Comment by dylanb** [comment]
the `type="tel"` does not match the `autocomplete="cc-number"`

**Comment by WilcoFiers** [comment]
Yeah, if you look here:
https://www.w3.org/TR/html52/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute

In the table, in the `cc-number` column you'll see that `Text` is the only supported control group. If you look at this field in a browser, you'll notice autocomplete doesn't work because it's on a type of element that doesn't support that autocomplete value.
