### ISSUE TITLE
fix false positive related to role="combobox"

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#160]
Has been reported in https://github.com/dequelabs/axe-firefox-devtools/issues/33

**Comment by dylanb** [comment]
The solution should be the following:

If the element on which the role has been placed is a native input element, then make the required children optional

**Comment by WilcoFiers** [comment]
I raised this issue on html-aria and Steve Faulkner got back on it. We have a different issue. Axe has two 'types' of 'owned' propertyes, 'all' and 'one'. All means every one of the roles is required, one means just one of them. ARIA doesn't actually ever require all children to be present. combobox is the only role in Axe which is set to require multiple children. Other uses of 'all' only has one role.

The fix is to change this to 'one'. Though I think it's probably better to also remove this difference all together as it adds unnecessary complexity.

**Comment by dylanb** [comment]
If there is a combobox implementation that does not use a standard input element and also does not have a textbox child, then this will have severe compatibility issues when a screen reader is turned on. 

For that reason, I think we should still raise the issue if there is no native element (note: this would be a temporary solution until the issue gets resolved in ARIA).

**Comment by johncaseysmith** [comment]
Hey @dylanb, any updates on this? Does the [previously mentioned solution](https://github.com/dequelabs/axe-firefox-devtools/issues/33#issuecomment-171918557) still apply?

**Comment by adamliptrot-oc** [comment]
Hi, what's the current situation with this? I'm running into this issue with automated testing.

**Comment by isner** [comment]
Proposed solution: https://github.com/dequelabs/axe-core/pull/481

**Comment by marcysutton** [comment]
Fixed with #481.
