### ISSUE TITLE
Getting "Form elements do not have associated labels" on Lighthouse even though they are present

### ISSUE THREAD

**Issue by gulatigautam** [dequelabs/axe-core#1727]
Ran lighthouse on www.americanexpress.com

Expectation: Should not be Getting "Form elements do not have associated labels" on Lighthouse since they are present

Actual: Getting "Form elements do not have associated labels" on Lighthouse even though they are present

<img width="882" alt="Screen Shot 2019-07-26 at 4 10 31 PM" src="https://user-images.githubusercontent.com/13562914/61980467-d85dfd80-afc4-11e9-8a69-90104ffd9e2a.png">
<img width="1049" alt="Screen Shot 2019-07-26 at 4 10 42 PM" src="https://user-images.githubusercontent.com/13562914/61980475-df850b80-afc4-11e9-93d9-2b9d211e53e7.png">

Then added axe extension to chrome and analysed it. Seeing "Form elements should have a visible label" even though an explicit label is present.

<img width="1394" alt="Screen Shot 2019-07-26 at 4 44 23 PM" src="https://user-images.githubusercontent.com/13562914/61980491-ead83700-afc4-11e9-9b38-a35c0c8a35e8.png">

**Comment by WilcoFiers** [comment]
@gulatigautam This is a correct error. As the axe extension reports, the label is hidden. Because of that, it will not get announced to assistive technologies. You can see this as well if you look at the accessibility tree in the devtools inspector. The best thing to do here is to make the label visible, rather than rely on the placeholder to provide a visible label. This would require a change in the design though. If you want to solve this problem for assistive technologies, you could do a number of things. My suggestion would be to include a title attribute on the inpug elements that contains the label text.

**Comment by gulatigautam** [comment]
@WilcoFiers Thanks for the comment. I am sorry I did not get when you said the label is hidden. If you see the snapshot above the labels for both "login-user" and "login-password" fields are explicit labels and they are not hidden. In fact this is very similar to the explicit label example mentioned here https://dequeuniversity.com/rules/axe/3.2/label-title-only?application=AxeChrome.

**Comment by straker** [comment]
The label for the login user and login password have `display: none` on them, and the visible label for the input is being provided by the placeholder text of the input.

![image](https://user-images.githubusercontent.com/2433219/62149185-633a4300-b2b8-11e9-91a0-9e97c63792c6.png)
![image](https://user-images.githubusercontent.com/2433219/62149222-73522280-b2b8-11e9-832a-c708d19b0acf.png)

As such, there is no associated label for the input in the accessibility tree

![image](https://user-images.githubusercontent.com/2433219/62149257-8bc23d00-b2b8-11e9-9bc6-811c1bb8dfac.png)
