### ISSUE TITLE
Non localized messages

### ISSUE THREAD

**Issue by thiagoeec** [dequelabs/axe-core#1750]
Expectation: Localized message for this messages:
`Fix any of the following / Fix all of the following`

Actual: English messages only.

Motivation: All messages to the user should be localized.

<pre><code>
axe-core version: 3.3.1

Using Axe bundled with Ace by Daisy (v 1.1.1).

For Tooling issues:
- Node version: 11.4.0 
- Platform:  Windows 10 x64 1903
</code></pre>

**Comment by WilcoFiers** [comment]
We'll take a look. Localisations are maintained partially outside the axe-core main team, so it's not something we guarantee is always up to date.

**Comment by WilcoFiers** [comment]
Alright, so my initial assumption was wrong about this. The problem isn't that we don't have localisations of these strings, it's that we're not using them. The reason is that `failureMessage` is ignored in `Audit.prototype.applyLocale`:
https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/audit.js#L216

That definitely needs to be fixed.

**Comment by jeankaplansky** [comment]
@WilcoFiers, @straker : Should this be a release notes item for axe-core 3.4?

**Comment by padmavemulapati** [comment]
Dev task
