### ISSUE TITLE
Combo box pattern should pass scrollable-region-focusable

### ISSUE THREAD

**Issue by rikbrowning** [dequelabs/axe-core#1763]
Expectation: Combo box pattern should pass scrollable-region-focusable

Actual: Fails scrollable-region-focusable

Motivation: The combo box pattern found at [https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) should be accessible when the content is scrollable. Keyboard navigation is handled by arrow keys pressed in the input and should never receive focus. 

To reproduce go to [https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) and in the Example 1 change the CSS so the listbox has a height:20px and overflow-y:auto. You can then search D to bring up 2 results and run to see the errors. Whilst these controls do not have the necessary scripting to keep the selection visible that is not what this rule is addressing.

**Comment by straker** [comment]
That's a good point. We'll have to look into supporting this.

**Comment by WilcoFiers** [comment]
We're going to look at excluding anything owned / controlled by a combobox to solve this. We'll mark those for review.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core(v4.0.2) code, dated 2/10/2020, 
not seeing failure with `scrollable-region-focussible` for combox pattern.
test snippet:
`<div role="combobox"><ul id="target" role="listbox" style="width: 12em; height: 2em; border: dotted; overflow: scroll;"><li role="option" style="height: 15rem">Option</li></ul></div>`

Also reproducible in axe-core-v3.5.4
![Uploading image.png…]()

**Comment by MohammedAjaz** [comment]
This issue is still reproducible with aXe 4.6.0(axe-core 4.2.0) with the same steps mentioned above
URL:  https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html 
Example 1 change the CSS so the listbox has a height:20px and overflow-y:auto. You can then search D to bring up 2 results and run to see the errors.
![ScrollableRegionIssue_axe_core](https://user-images.githubusercontent.com/70727392/98058493-ba9f5b00-1df9-11eb-836d-0cfb94e5c7de.jpg)
