### ISSUE TITLE
tabindex > 0 flagged as serious violation

### ISSUE THREAD

**Issue by jasonkiss** [dequelabs/axe-core#18]
Tabindex values > 0, while to be avoided in most cases, do not necessarily impact accessibility, and could in some cases improve it. Should just be a warning to ensure that tabindex values do not negatively impact meaning or focus order.

For example, the positive tabindex values in the YouTube iframe at http://www.deque.com/products/fireeyes/fireeyes-resource-center/fireeyes-installation-video/ (tested using aXe plugin for Chrome).

**Comment by dylanb** [comment]
This should be labelled as a serious best practice

**Comment by dsturley** [comment]
Merge from rules erroneously referenced.

**Comment by dsturley** [comment]
Existing rule is a good candidate for a "best practice".  However, we may want to add an additional rule that checks:

If a positive tabindex is used, it is used consistently and correctly.  For example, the following should not flag a violation:
    
        <a href="#" tabindex="1231">One</a>
        <a href="#" tabindex="1231">Two</a>
        <a href="#">Three</a>

This should flag a violation, as the elements with a positive tabindex will be focused before the implicit tabindex="0":

        <a href="#">Three</a>
        <a href="#" tabindex="1231">One</a>
        <a href="#" tabindex="1231">Two</a>

Tabindex should not decrement or decrease in value, the following should be a violation:

        <a href="#" tabindex="2">One</a>
        <a href="#" tabindex="1">Two</a>

It should also exclude `tabindex=-1`, meaning the following would not be a violation:

        <a href="#" tabindex="-1">Three</a>
        <a href="#" tabindex="1231">One</a>
        <a href="#" tabindex="1231">Two</a>

The only tricky part is that we would want to make the comparison for each frame, not the entire document; as each frame's `tabindex` is specific to the frame.

However, will require new functionality in core; to allow for "after" functions to be run for each frame rather than the entire document.  I've been contemplating this feature for a while, just did not have a use case for it.

**Comment by dylanb** [comment]
@jasonkiss's scenario, where tabindex can be used to improve usability, if done well, includes scenarios which might violate this newly proposed rule.

e.g. suppose I have a video player with controls that use floats and I want to use tabindexes to ensure that the visual layout matches the DOM without having to change all of my CSS (this is an actual use case that was discussed recently on the a11y slack)

Under this scenario, the tabindexes would increase as you encounter elements in the DOM.

@jasonkiss - is this the type of scenario you were thinking about?

**Comment by jasonkiss** [comment]
Snap! Exactly the sort of scenario (floats) that I was thinking of. I
suspect it will be extremely difficult to map out, based purely on the
HTML, those situations where positive tabindex values are always an
absolute violation. Might be best to restrict the rule to recommend manual
inspection with a strongly worded message about "best practice".

**Comment by dylanb** [comment]
@dsturley I think we should just move the rule to best practice
