### ISSUE TITLE
Consider a mode that evaluated hidden content

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#1833]
Consider adding a setting that evaluates everything under display:none and hidden elements, that will likely become visible at some point after page load. This would not be part of the main results... it could be one more category in the drop down.

 
![image](https://user-images.githubusercontent.com/2365411/65892459-57c8ce00-e374-11e9-9dcf-ada844cd6dd7.png)

**Comment by WilcoFiers** [comment]
Hey David. Thanks for the feedback. We've had this feature request a few times in the past. We are going to look into how we could possibly do this, but there are a few problems here.

1. Hidden DOM content is becoming less common. It's stuff that happened a lot in the jQuery era, but it's not really the way modern JS stuff is done. I have my concerns about how useful this is. Is this something you've gotten a lot of value out of for other testing tools?

2. The accuracy of this is questionable. For any hidden content you have to make the assumption that 1. It will be made visible at some point, and 2. that it won't be modified before it's made visible. I don't know how reliable this can be done.


Can you explain what the problem is you are trying to solve with such a feature?

**Comment by WilcoFiers** [comment]
@DavidMacDonald We've looked at this suggestion a little more closely, and have explored a few solutions. We've found a number of issues with testing hidden content that can cause false positives, which is something we have to avoid. Because of that, we are going to take it in another direction.

I appreciate the feedback! Stay tuned.
