### ISSUE TITLE
Accessibility test rules

### ISSUE THREAD

**Issue by spolamraju** [dequelabs/axe-core#184]
We are using axe-core to perform accessibility test against our application. We found it is very helpful and quick to integrate with many frameworks. We found as of now axe-core supports 47rules defined in following readme file.
https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md

We used Quailjs.org earlier which was covering more than 250 rules for accessibility test. 
Is there a plan to add more rules in axe-core in future? If yes then anytime line you guys have decided.

**Comment by WilcoFiers** [comment]
Hihi! Yes indeed, we are actively developing rules for Axe. We have released it as part of Attest, which is our commercial version of Axe. If you want a sneak peak what's coming down the line, that's where to look! But anyway, axe-core and Quail are quite different (I should know, I contributed quite a bit to both, glad you like it!!)

Axe is never going to have the number of rules QuailJS does, because with axe we have to make sure that there are no false positives. That means no 'this is probably wrong', so let's report it. Or at least, that's not going to be in axe-core. Axe is designed to go into CI processes, so anything that might break the build for the wrong reasons is a no-go in our book.

That's not to say there can't or won't be extended rule sets. But such rules will probably end up in a different library. Anyway. If you find this sort of rule writing stuff interesting, I suggest you check out the Auto-WCAG Community Group at the W3C. A whole bunch of us are looking to take this rule work one step further and come up with a more formalised approach. For now, I'm going to close this topic, as this is more of an open question then an issue. Feel free to keep sharing your feedback with us and thanks for leaving a message!
