### ISSUE TITLE
a11yCheck on YouTube is much slower than on other sites

### ISSUE THREAD

**Issue by mgerakis** [dequelabs/axe-core#191]
The performance of a11yCheck and also the aXe chrome extension seems to be much slower on YouTube than on other sites, sometimes taking greater than 15 seconds to finish.

**Comment by dylanb** [comment]
Thank you for your feedback @mgerakis! The performance is going to depend on the complexity of the page. Very large and complex pages with a large number of HTML elements will take longer than other pages. This is mostly due to the color contrast rule. If this is taking too long, you can turn this off when calling a11yCheck using the options argument.

I am going to close the issue but if you have performance problems on pages that are not complex, please post examples and we will gladly look at them.
