### ISSUE TITLE
`aria-controls` must point to a (unique) id

### ISSUE THREAD

**Issue by Malvoz** [dequelabs/axe-core#1927]
Currently, unless I'm mistaken, `aria-controls` pointing to an `id` that isn't existing in the DOM isn't flagged by aXe.

**Comment by scurker** [comment]
@Malvoz There's some scenarios where this could generate a false positive. For example, an element with `aria-controls` and `aria-expanded="false"` is not currently flagged as an issue because the controlled element may be generated via dynamic code.

Do you have a specific example you could provide where it should be flagged?

**Comment by Malvoz** [comment]
I suspected I wasn't taking into consideration all the things. I'll go ahead and close this. Thanks @scurker!
