### ISSUE TITLE
get-background-color Does not reset horizontal scroll

### ISSUE THREAD

**Issue by emilyrohrbough** [dequelabs/axe-core#1951]
## summary
https://github.com/dequelabs/axe-core/pull/1845  was merged & released to
> [check] if the center point of the element is within the viewport and if not, look for a scrollable parent element and scroll it.

This feature introduces the bug where it does not reset the horizontal scroll after the test is complete.

### Expectation:
Horizontal content is scrolled and is restored to its initial state.

### Actual: 
Horizontal content is scrolled and is **not** restored to its initial state.

## More Info
We use axe to run accessibly and visual regression on test pages. The following screenshot shows the before (deleted) and after (added) visuals. Before is running axe 3.2.0 on the page then taking a screenshot. After is running axe with 3.4.0.

<img width="747" alt="Screen Shot 2019-12-18 at 4 22 55 PM" src="https://user-images.githubusercontent.com/14099737/71128474-e4846a80-21b2-11ea-85de-296ec78ccd3e.png">

<pre><code>
axe-core version: 3.4.0
~axe-webdriver, extension or other integration version: X.Y.Z~

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v10.17.0
- Platform:  Mac
</code></pre>

**Comment by straker** [comment]
Thanks for letting us know. We're working on a major change to the color-contrast rule should fix this issue.

**Comment by benbcai** [comment]
@straker After taking a closer look at the cause of the issue presented in the above screenshot, it  is not #1845 that introduced the issue. It was the change made on #1599 that caused this. I tested our application without that [change](https://github.com/dequelabs/axe-core/pull/1599/files#diff-16259ae34de15a4e787e7c99f946e740) and I continue to get the before (deleted) screenshot and our tests passed. Once I included the check for the `hidden` overflow style from #1599, then I would get the  after (added) screenshot. 

Our application has another test example that also failed because the `overflow` style on its element is `hidden`. It appears to me that these hidden overflow elements initially get scrolled to a different position but does not restore back to the top-left position because the scrollableX and scrollableY variables [here](https://github.com/dequelabs/axe-core/blob/v3.3.0/lib/core/utils/get-scroll.js#L32-L38) are no longer evaluates to true.

**Comment by jeankaplansky** [comment]
ID'd as color-contrast issue. We're going to make one entry into the release notes for all color-contrast fixes/enhancements.

**Comment by benbcai** [comment]
@jeankaplansky @straker Would it make issue tracking easier if I log a separate issue for the root cause of the issue I mentioned above relating to the changes made in #1599? The color-contrast fixes/enhancements you're making would not fix the issue this issue.

**Comment by straker** [comment]
Ya, this issue has already been flagged as fixed, so probably best to create a new issue to track it.

**Comment by benbcai** [comment]
@straker @jeankaplansky I logged #1979 to restore scrolling for elements with `hidden` overflow style. Can you please review and prioritize as this issue is preventing my team from upgrading to V3.4.0 to fix other issues?

**Comment by padmavemulapati** [comment]
Larger pages also not taking more than 11s , attached screenshot
![image](https://user-images.githubusercontent.com/47409579/74041217-43b06f80-49eb-11ea-92c8-11f923cd3c5a.png)
