### ISSUE TITLE
Docs: finding latest version of a rule's doc is difficult

### ISSUE THREAD

**Issue by paulirish** [dequelabs/axe-core#2164]
Motivation: I wanted to read the axe docs on image-alt, so i googled [`axe image-alt`](https://www.google.com/search?q=axe+image-alt). The top result is the [2.6 docs for image-alt](https://dequeuniversity.com/rules/axe/2.6/image-alt). I personally know from past experience that these docs are version pinned and there may be a later version. A click and a manual URL edit later and I was looking at the latest (3.5) version of those docs. ;)

Naturally not everyone knows that these docs are version pinned, so there may be plenty of people looking at docs that are no longer updated.

-------

I feel like there are two possible solutions to consider here.

1. On non-latest docs, add a link to the latest version. That way I would have clearly known there's fresher content. 
1. Use `rel=canonical` to always point to the latest version. That way, the search results should be pointing there instead of whatever has the most googlejuice. (I'm not an SEO expert, but this does feel like a usecase that rel=canonical was designed for)

---------

just offering an idea, no biggie. cheers y'all!

**Comment by mohanraj-r** [comment]
I have come across this inconvenience too. I have seen jest snapshots tests fail when axe is upgraded because the help URLs in the axe results contain the version in the URL.  Wish there was a way to decouple the version number from the rule help url. Would it be possible to use e.g. `latest` in the help URL `https://dequeuniversity.com/rules/axe/latest/<rulename>` or we could remove any version info from the URL e.g. `https://dequeuniversity.com/rules/axe/<rulename>`  and then add info in the page about the status of the rule - e.g. which version it was added, deprecated, or removed etc.

**Comment by WilcoFiers** [comment]
Hey folks. Apologies for the slow response. Both excellent suggestions. I'll see what we can do here.

**Comment by jeankaplansky** [comment]
Taking up conversation with @paulbohman re: out-of-date index return results.

**Comment by paulbohman** [comment]
I have added the old versions of the rules to the robots.txt, with a disallow statement for each one:
https://dequeuniversity.com/robots.txt
This is something we will need to pay attention to as we keep adding new versions of the rules, but the disallow statement is supposed to prevent Google and other search engines from indexing old versions. The search engine will index the current version.
