### ISSUE TITLE
Role of "row" requires container with role table, grid, rowgroup, or treegrid

### ISSUE THREAD

**Issue by plweil** [dequelabs/axe-core#2203]
Expectation: Axe will create an issue that "Certain ARIA roles must be contained by particular parents"

Actual: Axe does not create an issue

Motivation: According to [Accessible Rich Internet Applications (WAI-ARIA) 1.1](https://www.w3.org/TR/wai-aria/#row): 

"Authors MUST ensure elements with role row are contained in, or owned by, an element with the role table, grid, rowgroup, or treegrid."

Failing to meet his requirement is a violation of [WCAG Success Criterion 1.3.1:](https://www.w3.org/TR/WCAG21/#info-and-relationships):

Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text

HTML pattern tested:

```html
<table role="presentation>

<colgroup>
<col>
</colgroup>
<colgroup>
<col>
</colgroup>
<colgroup>
<col>
</colgroup>


<tbody>
<tr role="row">
<td role="gridcell"></td>
<td role="gridcell"></td>
<td role="gridcell"></td>
</tr>

<tr role="row">
<td role="gridcell"></td>
<td role="gridcell"></td>
<td role="gridcell"></td>
</tr>

<tr role="row">
<td role="gridcell"></td>
<td role="gridcell"></td>
<td role="gridcell"></td>
</tr>

etc.

</tbody>
</table>
```

<pre><code>
axe-core version:3.5.1
axe-webdriver, extension or other integration version: Chrome (MacOS) extension v. 4.4.1
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Putting a note here for future reference.

It seems we [do not take into account parent roles](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/aria/aria-required-parent-evaluate.js#L35-L37) when determining required parents. We only use an HTML selector to check the node. And since `role=presentation` [does not remove explicit roles from the accessibility tree](https://www.w3.org/TR/wai-aria-1.1/#presentation), this should be considered a failure of `aria-required-parent` as the `role=row` node does not have the required `rowgroup` parent (the implicit role value of the `tbody` has been removed by the `role=presentation` on the table).

**Comment by plweil** [comment]
Thanks @straker. I would just note that in this particular case, there doesn't seem to be any reason for using `role-presentation` on the `table` parent. If the coder had simply left it as `table` with no aria role, or applied `role=grid`, it would have been valid (I think).

**Comment by WilcoFiers** [comment]
Yeah, I don't think this table is valid ARIA. It would be if the row / gridcell roles were removed. If you put role=presentation on a table, that role is applied to all rows / cells too. But not if those are explicitly declared to be something else.

What I'm more interested in is if it actually matters to users. My guess is it doesn't. AT tend to just look at the group roles to announce what a thing is, and just treat whatever is inside it as the thing that is supposed to be in the group. If you create a list with children without listitems, the only place where that causes issues is in IE.

Let's do some testing with tables to figure out if this creates inconsistent behaviour. If not, perhaps this should just go into review. Definitely something is odd about a table like that. I'm not ready to call this one a bug yet though, so I'm changing the label on that.

**Comment by straker** [comment]
Alright, so after testing this here's what we discovered:

Firefox/NVDA, IE11/JAWS, and Chrome/Talkback all read the contents of the table as just individual text items, so no problem there. However, the Safari/VoiceOver thinks the page is empty. Specifically, the use of `role=row` causes the contents of the table to disappear from VoiceOver. Since this is definitely a problem we are going to mark this as a failure.

**Comment by plweil** [comment]
@WilcoFiers @straker , Aside from the specific issue with VO, I wonder how the invalid ARIA affects users' awareness of table/grid relationships; i.e, understanding that text item x is in row n, column y, etc. Or is reading table contents as individual text items with no context (i.e, this is a table or grid) acceptable?

**Comment by straker** [comment]
With the `role=presentation` on the table, even without any overriding roles, all table semantics are removed from screen readers (which is to be expected)

**Comment by plweil** [comment]
yes, of course. An automated tool like Axe can't know that by adding `role=presentation`, the developer sabotaged the entire purpose of the page, which in the cases I audited is clearly to display a data table. It's not technically illegal, but it's a failure to make the content accessible nonetheless. Just a thought --might it be helpful for Axe to add a warning about applying `role=presentation` to parent elements -- or maybe it does already? E.g., 

> by applying `role=presentation` to a parent element, you are removing all native semantics from all child elements. Is this what you want?

**Comment by straker** [comment]
@plweil this should now be fixed in the latest develop version of axe-core. Would you mind pulling down [axe-core@next](https://www.npmjs.com/package/axe-core/v/next) and testing it? You should now see an `aria-required-parent` error for the missing parent roles due to the `role=presentation` on the table

**Comment by padmavemulapati** [comment]
tested with the test file `<table role="presentation> `
not seeing error for `aria-required-parent` 
![image](https://user-images.githubusercontent.com/47409579/89428810-6b924d00-d75a-11ea-8149-4b6017632963.png)

**Comment by jeankaplansky** [comment]
no user-facing docs required
