### ISSUE TITLE
docs: Extend fallback role explainer

### ISSUE THREAD

**Issue by eps1lon** [dequelabs/axe-core#2257]
Currently `<div role="none presentation" />` fails with the message
`Use only one role value, since fallback roles are unsupported in older browsers`

Expectation:
- List/link what axe considers "older browsers"
- what happens if they're unsupported?

Actual: 
None of the above

Motivation: 
I'd like to understand the rationale

Added in https://github.com/dequelabs/axe-core/pull/1970

**Comment by WilcoFiers** [comment]
Thank you for the suggestion. You can find the baseline axe-core uses here: 
https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md

The reason axe-core doesn't report this is because we don't know. There is no list of all the different roles / attributes / other features in HTML and ARIA, across all major browsers and screen reader combinations. There is **some** data, so we can tell for sure something doesn't work in all the things in axe-core's baseline, but there isn't enough that axe-core could provide sufficient information.

I definitely know fallback roles don't work in Internet Explorer, but I don't know if it works in other major browser / ATs, and to what extent it does. This information just doesn't exist, so while this definitely is something we would like to provide, this is not possible at this moment. We are involved in a number of project to put such information together though, so hopefully at some point in the future this becomes possible.

My recommendation would be to either follow axe-core's "unsupported" suggestions, or to test this out yourself with the AT important to your website.
