### ISSUE TITLE
Chrome 83 cannot see axe tab on devTool

### ISSUE THREAD

**Issue by linjin-harvey** [dequelabs/axe-core#2287]
Expectation: Using axe extension on chrome browser

Actual: I cannot see axe extension on chrom browser

Motivation: chrome upgrade to 83 since company security compliance

<pre><code>
axe-core version: 4.5.2
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Chrome  83.0.4103.61
</code></pre>

**Comment by linjin-harvey** [comment]
![image](https://user-images.githubusercontent.com/16532219/84467776-aecac500-acaf-11ea-9fdf-7dd0bd7eb6e7.png)

**Comment by straker** [comment]
Interesting. I can see the extension in Chrome 83. Are you saying you use to have the extension in the tabs but now you cannot once you upgraded?

![image](https://user-images.githubusercontent.com/2433219/84511751-3b5f8e00-ac84-11ea-969d-e0cc4e44004c.png)

**Comment by jamespatrickwhite** [comment]
I'm also noticing the same thing with Chrome 83.0.4103.97 on MacOS 10.15.5. The axe entry, along with the webhints extension, have gone missing from the Developer Toolbar since upgrading. Each of the extensions are still enabled, and both show up in the Chrome Menu toolbar at the top right of the browser window. No errors are shown in the browser console.

**Comment by straker** [comment]
This appears to be an issue with Chrome and certain sites. Some sites are preventing the loading of extensions that use Chrome DevTools. A workaround is to open Chrome DevTools before navigating to the site you want to test.
