### ISSUE TITLE
Axe should error when there is a configuration mismatch between frames

### ISSUE THREAD

**Issue by AdnoC** [dequelabs/axe-core#2340]
Steps to reproduce:

* Go to page with iframes (tested with https://github.com/dequelabs/axe-core-npm/blob/feat-disable-fram/packages/puppeteer/test/fixtures/nested-frames.html which contains an iframe of https://github.com/dequelabs/axe-core-npm/blob/feat-disable-fram/packages/puppeteer/test/fixtures/frames/foo.html)

* Paste `axe.min.js` into the console at the top level

* Paste `axe.min.js` into the console within the context of the iframe

* Run `await axe.run()`. It will contain violations from within the iframe

* Run `axe.configure({ branding: { application: 'axe-puppeteer' } })`

* Run `await axe.run()`. It will **not** contain violations from within the iframe

Expectation: Configuring branding has no affect on what violations are found

Actual: It makes iframes no longer produce violations

Motivation: We use branding in `@axe-core/puppeteer` and we want iframes to not be broken

<pre><code>
axe-core version: 3.5.3

Browser and Assistive Technology versions

For Tooling issues:
Chromium Version 78.0.3882.0 (Developer Build) (64-bit)
- Platform: Windows
</code></pre>

**Comment by stephenmathieson** [comment]
I believe this is also due to the same bug causing #2347

**Comment by straker** [comment]
We determined that this isn't a so much a bug in axe as it is a lack of documentation / error reporting. The doc issue is that when you configure axe, you need to do the same configuration in every iframe. So if you add branding or disable rules, you need to do that for each iframe as well.

The error reporting issue is that we silently fail in these cases. We should try to detect when axe is configured differently in iframes vs the main frame and report an error rather than fail so users know what the solution is. We just have to be careful we aren't throwing errors for iframes that have message listeners that aren't axe.

**Comment by WilcoFiers** [comment]
Documentation is added here: #2392. We still need to do some work to catch this in the future. I'll leave this ticket open for that purpose. Taking it out of the 4.0 milestone though.

**Comment by straker** [comment]
Closed via comments in #2521
