### ISSUE TITLE
Test without change html page

### ISSUE THREAD

**Issue by sbollu** [dequelabs/axe-core#237]
Hi,

I would like to know is there a way to test all html pages with out adding script in every page. Basically i have around 50 pages and i don't want to edit every page add axe script to run tests. 

Thanks,
Sri.

**Comment by marcysutton** [comment]
Hi, I would recommend taking a look at [axe-webdriverjs](https://github.com/dequelabs/axe-webdriverjs) for that. You could write tests that hit all of your pages, and the library will inject aXe for you. Otherwise, you'd have to write some sort of script to iterate over a list of pages and pass each one to the aXe API–we don't offer support for that in the open source library, but our [Attest family of tools](http://www.deque.com/products/worldspace-attest/) covers it (Attest is a product, and not open source).
