### ISSUE TITLE
Bullet - Provides list of rules and elements that passed accessibility checking, ensuring rules have been run against entire document

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#239]
The last bullet under 'Introduction' (https://github.com/dequelabs/axe-core/blob/master/doc/API.md#section-1-introduction) is unclear - "Provides list of rules and elements that passed accessibility checking, ensuring rules have been run against entire document." Can someone explain what it means?

**Comment by marcysutton** [comment]
It helps to determine whether the tests actually ran against the document, helpful for things like shallow DOM testing....which has a gotcha in that your DOM must be attached to run aXe tests (otherwise the tested nodes would be empty). If the report didn't include which elements were tested, you'd have no idea if there were actual violations. The list helps in the debugging process.
