### ISSUE TITLE
Getting java.lang.RuntimeException: Error when removing sandbox from iframes in Selenium with java

### ISSUE THREAD

**Issue by LakshmiNagandla** [dequelabs/axe-core#2551]
Software dependency versions used:

com.deque.html.axe-core : 4.0.0 

Calling methods: 

When we call the method : Results result = builder.withoutIframeSandboxes().analyze(driver)

and

Results result = builder.analyze(driver)

Error that we are getting: 

"java.lang.RuntimeException: Error when removing sandbox from iframes"

Note: For few of the other applications, the Analyzer method is working as expected.  But on few applications, throwing above exception message. 

Can any one please check share what exactly issue with AXE or application side?

**Comment by jeeyyy** [comment]
@LakshmiNagandla thanks for reporting.

For context this issue was also discussed on Gitter - https://gitter.im/dequelabs/axe-core?at=5f86e0ec07361f0cc64eeaab

Based on following the conversation between @LakshmiNagandla and @satishdeque it seems like the issue occurs only when a page contains an iframe.

@AdnoC can you investigate this further and get back to @LakshmiNagandla. Thanks.

**Comment by AdnoC** [comment]
Hi. While we had the `withoutIframeSandboxes` method, we forgot until 3 months ago (https://github.com/dequelabs/axe-core-maven-html/commit/a7959c5712aefae7fa003a75e956fa5275bc82a3) to not remove sandboxes by default. Can you try running the tool with the newest version, without using the `withoutIframeSandboxes` method?

If it is still causing issues, what page are you trying to test?

**Comment by WilcoFiers** [comment]
I'm going to close this. This issue is in the wrong repo.
