### ISSUE TITLE
aria-valuenow question? 

### ISSUE THREAD

**Issue by minoseah629** [dequelabs/axe-core#2639]
Expectation: span has a role slider and span has inner input, if the value is set yet, no error shown

Actual: an error of Ensures elements with ARIA roles have all required ARIA attributes: Required Aria Attribute not present: aria-valuenow
https://demos.telerik.com/kendo-ui/rating/index

Motivation: If the current value is not known (for example, an indeterminate progress bar), the author SHOULD NOT set the aria-valuenow attribute. If the aria-valuenow attribute is absent, no information is implied about the current value.
extracted from: https://www.w3.org/TR/wai-aria-1.1/#aria-valuenow
 if user has selected a value, the aria-valuenow is proper.

<pre><code>
axe-core version: 4.0.2 (axe - Web Accessibility Testing chrome extension) and (accessibility insight for web edge extension)
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: not applicable
- Platform:  windows
</code></pre>

**Comment by straker** [comment]
Thanks for the question. Looking this over we believe your use case is in fact a correct use case of not set `aria-valuenow`. However, even though the spec says you don't need to set one, screen readers try to default the `aria-valuenow` value to [halfway between the min and max](https://www.w3.org/TR/wai-aria-1.1/#slider) . This means that they read the value of the slider as `3`, making it appear as though the user has rated the item already. Because of this, you will need to set a value.

Since the value is not set though, the best "workaround" you could probably do is set the `aria-valuenow` property to something (maybe `0`?) and then use `aria-valuetext` to have the value read out as something that makes it clear the rating has not be set by the user.
