### ISSUE TITLE
Accessibility test results

### ISSUE THREAD

**Issue by angela-choo** [dequelabs/axe-core#268]
Is it possible to write the tests results to a file rather than display on command line?

**Comment by WilcoFiers** [comment]
Hi Angela
Axe-core does not have features build info it for this. Although we are
working to release aze-cli which can do this. I could recommend using
NodeJS to create your files. This is fairly straight forward to do.

Hope this helps!

On 16 Dec 2016 22:30, "Angela Choo" <notifications@github.com> wrote:

Is it possible to write the tests results to a file rather than display on
command line?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dequelabs/axe-core/issues/268>, or mute the thread
