### ISSUE TITLE
axe extension suppresses code highlighting script on getbootstrap.com

### ISSUE THREAD

**Issue by patrickhlauke** [dequelabs/axe-core#2686]
in Chrome at least, loading https://getbootstrap.com/docs/5.0/getting-started/introduction/ when the extension is active  blocks/overrides the JS-based code highlighting.

![Screenshot of the 'Starter Template' code block, showing no code highlighting](https://user-images.githubusercontent.com/895831/102059575-fbbb5f80-3de8-11eb-9c65-57cd7ce9da5f.png)

**Comment by scurker** [comment]
This appears to be related to #1868

**Comment by NathanPJF** [comment]
Sharing that this is also happening on other websites. Example: https://shopify.dev/docs/themes/liquid/reference/objects/selling-plan-group#selling_plan_group-options

* [Screenshot with Axe Chrome Extension disabled](https://screenshot.click/20-12-03gxz-h0zfu.png)
* [Screenshot of Axe Chrome Extension enabled](https://screenshot.click/20-12-68llg-ypm6i.png)

**Comment by darekkay** [comment]
I've noticed this on my [own blog](https://darekkay.com/blog/copy-shell-commands/) and the issue was driving me crazy. I thought it must be something with PrismJS or Chrome, until I found the real root cause.

But this also means that all my code examples are broken for axe web extension users (mainly because of #1868). Please prioritize this issue, as Axe users and people posting code examples on the internet are often the same group, and the Axe extension is messing things up.

**Comment by scurker** [comment]
Hey folks, we've implemented a fix for this and this will be rolling out in a release soon.
