### ISSUE TITLE
Zooming and scaling must not be disabled - maximum scale property value at least 2

### ISSUE THREAD

**Issue by TechThomas** [dequelabs/axe-core#278]
Why does the axe-core rule check for zooming values that support up to 500%?
meta-viewport-scale.js

The linked guidance references that the maximum scale property must not be less than 2.
https://dequeuniversity.com/rules/axe/2.1/meta-viewport?application=axeChrome

I know its a minor issue / best practice but I would like to request that it be consistent 
[Max Scale 2 Failing axe check](https://dl.dropboxusercontent.com/u/108383/MaxScale2.png)

**Comment by dylanb** [comment]
There are two separate rules:

1) A rule that raises a violation of WCAG if the viewport does not scale to at least 200%
2) A separate rule that raises a best practice if the viewport scales to > 200% but does not scale to 500%

This is intentional

Are you suggesting that the second best practice rule should not exist?

**Comment by jnurthen** [comment]
It is not a violation of WCAG if the viewport does not scale to 200%. It is a violation if there is not a mechanism to allow the text to scale to 200%. A valid way to meet WCAG is to have a font size preference that the user can set.

**Comment by dylanb** [comment]
@jnurthen if your application has this, then turn this rule off

**Comment by dylanb** [comment]
closing because the question was answered
