### ISSUE TITLE
Node is not defined

### ISSUE THREAD

**Issue by pauldcollins** [dequelabs/axe-core#279]
Hi there

I am setting up Axe Core for the first time and getting the current error. I have tried the suggestion mentioned in #206 (IE - checking if Node is undefined in 'normalizeContext'), but it hasn't solved the problem.

I'm using Protractor with Firefox and trying to run e2e tests. Are there any other suggestions to fix the problem? Here are my settings:

**Node version: v4.2.0
Firefox version: 47.0
Protractor Version: 3.3.0**

My code for the test is:

```
it('should have no a11y violations', function(done) {
    axe.run(function (err, result) {
      expect(err).toBe(null);
      expect(result.violations.length).toBe(0);
      done();
    });
  });
```

Let me know if you require further info. Thanks for any advice.

**Comment by marcysutton** [comment]
How are you including axe-core? I would recommend taking a look at [axe-webdriverjs](https://github.com/dequelabs/axe-webdriverjs), since it handles injecting axe for you. Here is a test file in a demo app that you can check out. https://github.com/marcysutton/axe-angular1-demo/blob/master/e2e-tests/scenarios.js

**Comment by pauldcollins** [comment]
Hi @marcysutton thanks for your assistance. I've finally had the chance to implement axe-webdriverjs and now it works perfectly. Cheers!

Appreciate the help and thanks for the great work you guys are doing on Axe Core.
