### ISSUE TITLE
Definition of Impact: Critical/Serious/Moderate/Minor

### ISSUE THREAD

**Issue by EvelynGaoGao** [dequelabs/axe-core#2798]
Hi, I noticed for each Axe core Rule-id, we have one to two impact level.  I was wondering how does Axe define impact for each rule? Are there any correlation between impact and Disabilities affected?

**Comment by straker** [comment]
The impact of a rule is determined by taking the highest impact level of all the checks the rule uses. Typically the higher the impact level, the more serious the problem is in terms of how it will affect users.

**Comment by EvelynGaoGao** [comment]
Thank you for your reply. My question turns to how do you define impact level for each rule?

**Comment by straker** [comment]
From @WilcoFiers 

> As for distinguishing between minor and moderate, this is fairly subjective. Axe-core's impact is determined by checks, which have a certain granularity. All things flagged by a check will have the same impact. In this particular case, moderate is an estimated average impact of this check. That means the impact should in many cases be considered higher, and in others lower.
> 
> Impact is highly context dependant. A missing alt attribute can be minor, or it can be a complete blocker. Impact as axe-core reports it is a fair starting point for prioritisation, but that's all they are, a starting point. I would recommend you always look them over and shift things higher or lower in the priority list depending on context.

**Comment by EvelynGaoGao** [comment]
One more further question. What criteria do you use when consider together from the context as a blocker critical/ serious/ medium/ minor?

**Comment by cchooley** [comment]
+1, this is an **awesome** tool but now that I've integrated it into our react codebases I'm getting questions about how actionable each tier of "impact" should be. I definitely understand a lot of this being context-dependent, but it would be nice to have a more concrete point of reference than what I'm seeing thus far.

**Comment by erik-deque** [comment]
Here is what we use for definitions of the severity levels:

- **Minor** - Considered to be a nuisance or an annoyance bug. Prioritize fixing if the fix only takes a few minutes and the developer is working on the same screen/feature at the same time, otherwise the issue should not be prioritized. Will still get in the way of compliance if not fixed. Should be very infrequent.
- **Moderate** - Results in some barriers for people with disabilities, but will not prevent them from accessing fundamental features or content. Prioritize fixing in this release, if there are no higher-priority issues. Will get in the way of compliance if not fixed. Should be fairly common.
- **Serious** - Results in serious barriers for people with disabilities, and will partially prevent them from accessing fundamental features or content. People relying on assistive technologies will experience significant frustration as a result. Issues falling under this category are major problems, and remediation should be a priority. Should be very common.
- **Critical** - Results in blocked content for people with disabilities, and will definitely prevent them from accessing fundamental features or content. This type of issue puts your organization at risk. Prioritize fixing as soon as possible, within the week if possible. Remediation should be a top priority. Should be infrequent.

We are looking at how we can incorporate this information into the axe DevTools Extension.

**Comment by dylanb** [comment]
Docs are now live https://github.com/dequelabs/axe-core/blob/develop/doc/issue_impact.md
