### ISSUE TITLE
Review fallback issues for role none/presentation on elements no implicit role

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2909]
The following shouldn't be failed. It'd be better to mark it for review instead. It **might** be an issue if the div is between a `menu` and `menuitem`, but pretty much any other case this isn't going to matter.

```html
<div role="none presentation">
<div role="presentation none">
```

**Comment by clottman** [comment]
Just wanting to double check here - in the [W3 WAI-ARIA docs on role=presentation and role=none](https://www.w3.org/TR/wai-aria-1.1/#role-presentation-note-none), I see a [note on using role='none presentation'](https://www.w3.org/TR/wai-aria-1.1/#role-presentation-note-none) but nothing on `presentation none`. 

Was it intentional @WilcoFiers to reverse the order from the suggested fallback usage? 

Just for my own understanding, I'm also not sure when you would use this snippet on a div. It seems like both `presentation` and `none` are meant to negate the default semantic role on an element, which a div doesn't have as I understand it.

**Comment by straker** [comment]
@clottman in this case order doesn't matter. `none` is a synonym for `presentation` so they both do the same thing. The `div` was an example, but the main issue is that if an element uses both `presentation` and `none` on an element without an implicit role, the [fallback role check](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/aria/fallbackrole-evaluate.js) shouldn't fail and should instead be marked as needs review.

**Comment by padmavemulapati** [comment]
Verified with latest codebase, develop branch , 
test snippet causing violation:
'<input type="text" id="target" role="presentation none"/>`
test snippet showing needs review:
`<div id="target" role="none presentation">Foo</div>`
 `<div id="target" role="presentation none">Foo</div>`

![image](https://user-images.githubusercontent.com/47409579/123264856-100ab280-d518-11eb-94e5-2740175ab52b.png)
![image](https://user-images.githubusercontent.com/47409579/123264935-24e74600-d518-11eb-8cb7-b7a29c0b1b39.png)
