### ISSUE TITLE
New runPartial and finishRun methods

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2936]
Since axe-core's use of window.postMessage() can interfere with the operations, we need a way to run axe-core that does not require window.postMessage. Browser extensions can use `axe.frameMessenger()` for this, which was released in axe-core 4.2. However using frameMessenger in APIs usually isn't possible, which is why in axe-core 4.3 we're going to introduce an alternative method of running axe-core.

With axe.runPartial() and axe.finishRun it will be possible to split an axe-core run into two phases. In the first phase, all frames are tested separately, and the results are collected in the correct order in the script driving the browser. Then in the second phase, those results are combined into an axe-core report. This will look something like this:

```js
// Recursively wait for the frame to load, inject axe, then find nested frames
// and return each frame (including top)
const frames = await setupFrames(page, context);
const frameResults = await asyncMap(frames, async ({ frame, frameContext }) => {
  const initiator = frame === page.mainFrame(); 
  return frame.execute(() =>
     axe.runPartial({ ...frameContext, initiator }, options)
)})
const axeReport = await blankPage.execute(async () => {
  await frame.execute(axeSource);
  return axe.finishRun(frameResults, options)
})
```

**Comment by stephenmathieson** [comment]
Might be late to the party, but it looks like we're creating our oven version of [async iteration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) using the fictitious `asyncMap` function. If possible, I strongly suggest using native JavaScript features rather than re-implementing them ourselves.

Perhaps the `setupFrames` function should return an async generator instead?
