### ISSUE TITLE
nested-interactive and `details` elements

### ISSUE THREAD

**Issue by connorjclark** [dequelabs/axe-core#2958]
This is enough to fail this rule:

```
<details>
    <summary>
      <a href=#>click</a>
    </summary>
    ...
  </details>
```

Is this intentional?

This is a simplified example of a failure seen for this element: https://lighthouse-n9rg3umip-googlechrome.vercel.app/english/#:~:text=these%20items%20address%20areas%20which%20an%20automated%20testing%20tool Even with `summary>a` fixed, I think we'd still fail b/c we have nested `details` elements. What is the suggested fix for this? `tabindex=-1` all the things until `details` is expanded?

**Comment by WilcoFiers** [comment]
Yeah, this is definitely a problem. If I check out those summary elements in VoiceOver, the link gets completely ignored. It's fairly complicated. Summary elements have a `button` role. In the ARIA specification of `button`, it is set to have presentational children. That basically means that everything inside a button will be treated as though it was text. That's why the link is ignored.

The tricky part here is that Chromium and Firefox no longer respect the ARIA standard on this. Safari still does, which is why in VoiceOver this problem exists.

I would recommend not using summary / details if you want to include anything beyond a simple label in the summary. Better to have a separate expand/collaps button.
