### ISSUE TITLE
Add rules for checking table header or role presentation

### ISSUE THREAD

**Issue by smustgrave** [dequelabs/axe-core#3011]
Axe currently does not check for table headers or role presentation.  Example https://www.ssa.gov/accessibility/andi/help/alerts.html?table_has_no_th

**Comment by WilcoFiers** [comment]
Thank you for the suggestion. This is something axe-core used to do in the `layout-table` rule. We took that out because it just wasn't accurate enough. Usually, you are right, it is an indication that something is wrong if a table has no headings. But there are plenty of exceptions to it.

For example, strictly speaking, WCAG doesn't really require `role="presentation"` on layout tables. It requires that you don't use `th`, `caption`, `header="..."`. It is certainly a good practice to use `role="presentation"` on layout tables, but at best it's a best practice. 

Secondly, WCAG requires every table to have headers. Most of them do, certainly. But some tables just don't have headings. And if they don't, there's no requirement to add them. Not until level AAA anyway. The Gmail inbox comes to mind. E-mails there are in a table with columns for sender, subject, date, etc. But there are no column headers above those, and there isn't really an obvious row header either.

If you want, it shouldn't be too difficult to create a custom rule that does what you're looking for. Most open source axe-core integrations don't support custom rules, but the commercial axe DevTools products do. There are other things in trusted tester that axe-core could test too with custom rules.


I'm going to close the issue. Again thank you for proposing this. We do very much appreciate it.
