### ISSUE TITLE
Switch from PhantomJS to headless Chrome

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#305]
https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE

I think we should do it ASAP.

**Comment by dylanb** [comment]
This feature should be available on all platforms on June 6, 2017 https://www.chromestatus.com/features/5678767817097216

**Comment by mfairchild365** [comment]
With my brief look at the Chrome headless documentation, it  looks like it would allow us to [check if elements have javascript event listeners] attached to them (https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger/#method-getEventListeners). I'm not sure how detailed this api is, but perhaps it could be used to determine if an element should be keyboard focusable or not, etc. 

Of course, using such a proprietary API would mean that the check would only work in headless chrome.

Just brainstorming. :)

**Comment by WilcoFiers** [comment]
@mfairchild365 Due to bubbling, that's unfortunately not a very reliable method. I'm also not sure we'd want to rely too heavily on vendor specific APIs. Axe-core is intended to work with any browser.

**Comment by mfairchild365** [comment]
@WilcoFiers Ah yes, I bubbling. I knew there was something that I was forgetting.

**Comment by jaimeiniesta** [comment]
> Chrome is faster and more stable than PhantomJS. And it doesn't eat memory like crazy.

I have high hopes on the change to Chrome headless. Let me know if I can help with this, maybe there's an experimental branch that I can try and provide feedback?

**Comment by joelgriffith** [comment]
I'd be interested in getting some accessibility API's into Navalia (github.com/joelgriffith/navalia). It's a phantom-js/nightmare web driver atop of headless-chrome. Please feel free to file an issue or PR!

**Comment by jaimeiniesta** [comment]
Hi, what's the plan with the switch to headless Chrome? Is 3.0.0 ready for it?

**Comment by WilcoFiers** [comment]
@jaimeiniesta It's not part of 3.0. I'm working on the Q2 roadmap for aXe at the moment, it's high on the list so there's a good chance we'll sort it out in the next few months.

**Comment by jaimeiniesta** [comment]
@WilcoFiers I'm a little confused with the `chrome-headless` requirement.

I'm currently running `axe-core` 2.5.0 through `axe-cli`, using phantomjs in an AWS Lambda instance, it works fine.

Now, I want to upgrade to `axe-core` 3.0.3. When I do this, I see that it uses `chrome-headless`, which confuses me because as per this issue, it's not currently supported, right? Or is it that when using `axe-cli` we do get support for `chrome-headless`?

`axe-core` 3.0.3 with `chrome-headless` works fine in my dev machine (OSX) but fails in my AWS Lambda. I need to fix this but before I dig into it, is `chrome-headless` supposed to work with the latest versions of `axe-core` and `axe-cli`? What NPM package should I use for `chrome-headless` in that case?

If not, is there a way to upgrade to `axe-core` 3.0.3 and keep using `phantomjs`?

Thanks!

**Comment by jaimeiniesta** [comment]
@WilcoFiers thanks! So, is there a way to upgrade to axe-core 3.0.3 and keep using phantomjs? When I tried to upgrade it, it started using chrome-headless. How can I specify that I want to keep using phantomjs?

**Comment by WilcoFiers** [comment]
For Axe-cli, no, you'll have to move to one of the major browsers. We build Axe-cli as a light weight way tool for running Axe locally, it's not exactly designed as a CI tool. Axe-webdriverjs / java are much better for that, so is [Attest Getter](https://www.deque.com/tools/worldspace-attest/).

It shouldn't be too difficult though to install Chrome on your CI machine. We've certainly done that before we moved to CircleCI v2.

**Comment by straker** [comment]
Completed via #1955 (no docs nor qa tasks)
