### ISSUE TITLE
Will and when will WCAG 2.2 be supported? 

### ISSUE THREAD

**Issue by telion2** [dequelabs/axe-core#3201]
My Client expects me to support WCAG 2.2, hence the tools that depend on this library need to support that WCAG 2.2. 

Are there plans to support WCAG 2.2, and do you have any estimate, when that could be? 
Is it a matter of weeks, months, years or is it a matter of being possible?

**Comment by WilcoFiers** [comment]
WCAG 2.2 has not formally been accepted as a W3C recommendation yet. It is under active development, so we are at least going to wait until it has further stabilized. Whether we'll put anything out before WCAG 2.2 makes it to recommendation or not is unknown, it depends on what the timeline for WCAG 2.2 will look like, which is currently unknown.

I'm going to close the issue, since there is no concrete action to come from this change. Just know that as soon as we can, we'll be adding WCAG 2.2 support, for as far as possible without false positives.
