### ISSUE TITLE
It takes me almost 5 mins to test a page by jest, but it is very fast on chrome when using react-axe.

### ISSUE THREAD

**Issue by pacific0437** [dequelabs/axe-core#325]
It is very slow, may be 260 seconds to finish the test.
However, when I use react-axe and watch result by the chrome's console, it runs fast.
I need to do the automatic test by the CLI, can anyone help me to improve the performance?

The config file:
```
const config = {
  rules: {
    'link-in-text-block': { enabled: true },
    'color-contrast': { enabled: false },
    label: { enabled: false },
    tabindex: { enabled: false },
  },
}
```
Using axe-core like this:

```
import axeCore from 'axe-core'

const reactAxe = function reactAxe(config) {
  return axeCore.run('#root', config)
}

export default reactAxe
```

append the root element to the body before test

```
const root = document.createElement('div')
root.setAttribute('id', 'root')
document.body.appendChild(root)
```

Form
```
class App extends React.PureComponent {
  render() {
    return (...)
  }
}
ReactDOM.render(<App />, document.getElementById('root'))
```
test it
```
import axe from '../js/axe-test'
import axeConf from '../axe-config'
import '../components/Form'

test('a11y test error for form', () => axe(axeConf).then(result => {
  expect(result.violations.length).toBe(0)
}))
```

**Comment by dylanb** [comment]
@pacific0437 this is because Jest is using JSDOM - which is sssssssslllllllllllllllooooooooooooooowwwwwwwwww

Is there a way to run Jest tests with a real headless browser instead?

**Comment by WilcoFiers** [comment]
We have a similar setup for our React component library (Mocha instead of Jest). We test each component separately, instead of testing an entire page. Those tests take up +/- 100ms. That still adds up.

Like @dylanb says, this is because of JSDOM. A headless browser takes some time to launch, but it well makes up for it once it's going and you have all the performance wins of a native DOM implementation. If that's not an option, I'd suggest you run axe on individual components rather then full builds. Having fine grained control like that is pretty useful because you more easily test different states of your UI.

**Comment by marcysutton** [comment]
I'm going to close this issue because there isn't much we can do about JSDOM performance–hopefully Wilco and Dylan's suggestions about testing individual components or using a headless browser instead will help speed things up.

**Comment by tyq340503** [comment]
jest-axe please
