### ISSUE TITLE
Can't Use aria-roledescription with role="heading"

### ISSUE THREAD

**Issue by johnmiroki** [dequelabs/axe-core#3294]
For:
```html
<h3 aria-roledescription="Card Header" tabindex="0" role="tab">Spot</h3>

//or

<div role="heading" aria-level="3" aria-roledescription="Card Header" tabindex="0" >Spot</div>
```
Product: axe Extension Chrome

Expectation: Pass validation

Actual: "Use aria-roledescription on elements with a semantic role"

Motivation: Want to understand why h3/role="heading" can't work with "aria-roledescription"

<pre><code>
axe-core version: 4.3.3
axe-webdriver, N/A

Browser and Assistive Technology versions Chrome 95

</code></pre>

**Comment by WilcoFiers** [comment]
Axe-core flags this as something to review. aria-roledescription doesn't get announced consistently by screen readers. Particularly on mobile there is no support for this:
https://a11ysupport.io/tech/aria/aria-roledescription_attribute

We're flagging this up so that you can check that if the information you're providing through role description is missing, your users aren't missing something important. In this particular case I would say you don't need to worry.
