### ISSUE TITLE
Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by finoz** [dequelabs/axe-core#3313]
Product: axe-core

Expectation: I'm including axe-core in a npm/webpack project with require('axe-core'), And I expect it's going to work

Actual: the inclusion (even if I don't initialize any script) causes the error in object:
`Error processing request: Error: Request body larger than maxBodyLength limit` 

Motivation: I rally want to use your product, dudes!
🙏
<pre><code>
axe-core version: 4.3.5

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 12.14.1
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment]
This is not an issue on axe-core. Wherever that maxBodyLengh comes from (it looks like Axios to me), you should look there for an answer. This looks like a configurable setting, so that should be fairly easy.

Why are you trying to webpack axe-core at all? You probably shouldn't have axe-core in your production code, and for development it'd be much faster to leave it as an external dependency.

**Comment by WilcoFiers** [comment]
Two weeks without response. Since I don't think this is an axe-core issue I'm closing it.
