### ISSUE TITLE
Cannot run checks in parallel

### ISSUE THREAD

**Issue by sfc-gh-sparker** [dequelabs/axe-core#3324]
Product: axe-core

Expectation: Perhaps not technically a bug, but I would like to be able to call multiple `axe.run`s in parallel in the same environment. Alternatively, I'd like to arbitrarily call axe a11y rule checks without going through `axe.run`.

Actual: I can't seem to get tests to run in a one-off manner via mechanisms like `axe.utils.getRule('img-alt').run()` and I think it has to do with setup configurations and the virtual dom being configured via `axe.run`. It might be making assumptions that just aren't true when being called this way. But I might also be doing it incorrectly, and if so, I apologize.

Motivation: I'm writing a tool that will run a11y checks on components once they're rendered. When there is an error, this produces a red box and a popover with more information. It looks like this:

![Screen Shot 2021-12-02 at 2 12 09 PM](https://user-images.githubusercontent.com/63472565/144495101-12d111dd-9877-41e8-95b4-42d9e8006123.png)

i run these checks after each React element renders (with various optimizations for performance). This is so that if they open a dialog or show more content etc., these checks will always be run over the newly-rendered HTML.

<pre><code>
axe-core version: 4.3.5

For Tooling issues:
- Node version: 12
- Platform: Mac
</code></pre>

**Comment by WilcoFiers** [comment]
First up, that's a really neat idea. I've heard folks talk about a red-box axe-core solution, but have yet to see someone build it. If it goes open source, be sure to add it to the [axe-core projects list](https://github.com/dequelabs/axe-core/blob/develop/doc/projects.md) once it's available.

The browser just isn't multi-threaded. Running in parallel isn't really possible. In theory we could change axe so that it can start multiple runs, but you'll just end up hoarding memory, and have the first run resolve slower without speeding up the second. The best we could probably do with that is to create a queue, so you can schedule future runs in parallel, but still have them executed serially. The trick there would be to ensure configuration is applied in the correct order, so you'd have to queue configuration calls too.

It's a pretty niche use case. This mutation observer scenario is the only one I've seen where this might come in handy. But it has come up before. I don't expect this is something we'd prioritise, given how niche this is. But if you're interested in contributing a PR, I certainly wouldn't be opposed to supporting the work.

**Comment by sfc-gh-sparker** [comment]
There is talk of open sourcing this, so I'll let you know if it does.

I had been doing more experimentation and playing around and we are essentially going the queue route, but I think it'll work really well after some initial tests. I get that it's pretty niche, but hopefully others will be able to benefit from it if I can get it open sourced. Thanks for the reply. 🙂
