### ISSUE TITLE
aria-roledescription issue being reported in a page that does not use the attribute

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#3337]
Product: axe-core

Expectation: Should not report a false error

Actual: Reports false errors for `aria-roledescription` on a  page that does not use that attribute

<pre><code>
axe-core version: 4.3.5
Chrome 96
</code></pre>

1. Go to the page (see https://dequesrc.atlassian.net/browse/CSD-18170 for the URL)
2. Open the console and inject the source code for axe-core 4.3.5 into the page
3. type `axe.run(document, (err, results) => { console.log(results);})` and execute the analysis
4. Inspect the `violations` array and note that there are nodes reported violating the rule listed above
5. Inspect the reported nodes and note that they do not use the aria attribute at all

**Comment by straker** [comment]
The page in question uses HTML elements that use JavaScript to override the native `getAttribute` with a custom function that will return an empty string for any attribute, even if the attribute does not exist on the element. It should return `null` in those cases but since it returns an empty string it's treated as existing on the element.
