### ISSUE TITLE
Contrast-error on list with more than one level

### ISSUE THREAD

**Issue by kjetilhansen0** [dequelabs/axe-core#3400]
List with more than one level generates error: "Text elements must have sufficient color contrast."

**How to reproduce:**
List with two levels or more. No CSS needed.

```
<ul>
  <li>Lorem
    <ul>
      <li>Ipsum</li>
    </ul>
  </li>
</ul>
```
Plugin says: "Element's background color could not be determined because it is overlapped by another element."
Tested with Axe-core and browser plugin. Chrome on MacOS.

**Comment by straker** [comment]
Thanks for the issue. We'll see if we can get this fixed for the next release.

**Comment by padmavemulapati** [comment]
Validated with the latest code base of axe-core develop branch,

with the code snippet:
```
<ul>
  <li>Lorem
    <ul>
      <li>Ipsum</li>
    </ul>
  </li>
</ul>
```
where nested `list` elements are presented, issue saying that, error is getting for "Text elements must have sufficient color contrast." 
Not seeing that error now, but seeing incomplete results for `color-contrast` saying 
"Element's background color could not be determined because it is overlapped by another element"
![image](https://user-images.githubusercontent.com/47409579/206958978-533afee0-3e78-42ba-89d4-164bef8e6caf.png)
