### ISSUE TITLE
Hidden input triggering insufficient color-contrast

### ISSUE THREAD

**Issue by filipewl** [dequelabs/axe-core#3514]
**Product**: axe Extension (axe DevTools Chrome)

**Expectation:** discard the color-contrast violation or better explain why the `input` is failing the [color-contrast](https://dequeuniversity.com/rules/axe/4.4/color-contrast) rule considering it's hidden, has no placeholder or text, or when it has text it doesn't fail the color-contrast.

**Actual:** 

When running the axe DevTools Chrome extension on the page https://nextjs.vtex.app/ with a 1000 x 600 screen dimension, axe reports a color-constrast violation associated with the element `<input data-store-input="true" data-testid="store-input" aria-label="search" placeholder="" value="">`. This element is hidden and it's also not clear what's causing the color contrast issue considering that when I run axe with the input visible and with some text, there's no color contrast violation.

![CleanShot 2022-06-23 at 12 37 05](https://user-images.githubusercontent.com/381395/175347162-28dc1c7d-020a-47b9-a387-53d92854c52e.png)

**Motivation:** I feel like there's some kind of mistake with the rule for selecting this element.

<pre><code>
axe-core version: 4.4.2
extension: 4.29.0

Chrome Version 102.0.5005.115 (Official Build) (x86_64)
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Looking at the issue reported, it looks like it might be reporting it as a Needs Review item rather than a violation. Is that correct? When I run axe it shows that it says axe is unable to determine color contrast. This is because the input is not "hidden" in the traditional sense (using CSS `display: none` or the `hidden` attribute), it's just that its width is set to 0. This is still "visible" so we try to run color contrast on the element. But since there's no text and small dimensions, we can't determine the contrast ratio, so mark it as Needs Review.

**Comment by filipewl** [comment]
> Looking at the issue reported, it looks like it might be reporting it as a Needs Review item rather than a violation. Is that correct?
You're correct! Sorry for the wrong terminology.

> This is still "visible" so we try to run color contrast on the element. But since there's no text and small dimensions, we can't determine the contrast ratio, so mark it as Needs Review.
I see. I'll try some other approach to see if that fixes it.

Thanks for the fast feedback @straker! I'm closing this for now.
🙇
