### ISSUE TITLE
Should regions be flagged as requiring accessible names?

### ISSUE THREAD

**Issue by sivakusayan** [dequelabs/axe-core#3585]
**Product:** axe Extension

**Expectation:** When scanning a [codepen with a nameless region](https://codepen.io/sivakusayan/pen/xxWjJpa), the extension would flag the nameless region as needing a name.

**Actual:** Nameless region is not flagged.

**Motivation:** Nameless regions aren't exposed as regions at all, at least [according to the CORE-AAM](https://www.w3.org/TR/core-aam-1.2/#role-map-region-nameless). This behavior is implemented in both Chromium and Firefox (not sure with Safari). I feel like this could be potentially confusing to authors who aren't familiar with these rules - that's what I often see with coworkers in my company, at least.

I see that this was previously discussed in #2421, and it was determined those names weren't necessary. I'm not sure how different the AAM and implementation statuses were back then, but would it make sense to revisit this issue for regions? Maybe this should be flagged as a best practice.

**Comment by WilcoFiers** [comment]
Hey @sivakusayan. Thanks for the suggestion. There's nothing inherently wrong with a region element without an accessible name though. Not all regions have, or need a name. You could say that regions that need a name, require a name, but there is no way to know whether regions need a name or not. Nothing accurate I can think of anyway.

This is sort of the problem with some elements. On something like `img` you can say if there is no alt, title, aria-label, that's an automatic failure. But if a `canvas` element doesn't have an accessible name, there's no way to know if that is because it should be ignored, or if there's a problem.

**Comment by sivakusayan** [comment]
> When you require names on things that don't have an obvious name, whatever name content authors then add is likely not going to be helpful.

I can see that. My initial thought was that some kind of name is better than none, since how would users distinguish different regions when pulling up a list of all landmarks? Although I guess that also applies to other types of landmarks, even though other landmarks don't require names. But if a user was merely cycling through all the regions on the page using virtual cursor hotkeys, I think the user can distinguish different landmarks from each other just by their content. I'm struggling to see a straightforward answer here 😕

I think I'm okay with closing for now, mostly because:

- This seems hard to automate in a useful way at first glance
- I suspect that the only reason WAI-ARIA required a `region` to have an accessible name is to match the behavior in CORE-AAM. Which in turn seemed to have only been changed to reduce issues with non-ideal markup, and not for any real usability concerns.
- The use of `regions` should hopefully be rare compared to other landmarks, making this a low impact rule even if we did care about this.
