### ISSUE TITLE
axe is struggling to determinate the background color when using nested lists

### ISSUE THREAD

**Issue by Zauberbutter** [dequelabs/axe-core#3626]
### Product

axe-core

### Product Version

4.4.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

I've found the following issue with the determination of background colors by axe. The source code contains an example where it fails and one where it succeeds. 

**How to reproduce**:
<details>
<summary>HTML</summary>

```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <style>
    *, ::after, ::before {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    body {
	    font-family: Arial,Helvetica,sans-serif;
        font-size: 14px;
        line-height: 1.6em;
    }
    </style>
</head>
<body>

<ul>
    <li>
        Test
        <ul>
            <li></li>
        </ul>
    </li>

    <!-- when you remove the dot at the end it fails too -->
    <li>Lorem <strong>ipsum</strong>. 
        <ul>
    	    <li></li>
        </ul>
    </li>
</ul>

</body>
</html>

```

</details>

**Product**: axe-core
**Expectation**: It should be able to determine the background color.
**Actual**: It can't.

<pre><code>axe-core version: 4.4.3
DevTools: 4.36.2</code></pre>

**Comment by straker** [comment]
Thanks for the  issue. It looks like we'll need to figure out how to handle this type of code as we currently think the nested `li` is overlapping the parent `li`.  Even `document.elementsFromPoint` reports it the same way.

**Comment by padmavemulapati** [comment]
Validated with the latest code base of axe-core develop branch, 
when using nested list elements with background color, it is taking care of `color-contrast` things not `list` which is expected.
When Nested list elements are presented, issue saying that, error is getting for "Text elements must have sufficient color contrast."
Not seeing that error now, but seeing incomplete results for color-contrast saying
"Element's background color could not be determined because it is overlapped by another element"
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/47409579/206959946-aa4aba8d-5868-4f32-8b60-ca08d2b2734a.png">
