### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by AlyssaLemon** [dequelabs/axe-core#3733]
<< Please describe how you encountered this issue >>

axe-core version: `4.4.2`
axe-extension version: `4.37.1`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167249
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167219
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167169
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167065
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:166733
    at Array.map (<anonymous>)
```

**Comment by straker** [comment]
Thanks for the issue. Is the site where you encountered this issue public that we could try to replicate the issue? If not, could your try running axe-core directly on the page and/or using one of our [axe-core integrations](https://github.com/dequelabs/axe-core-npm/tree/develop/packages) to see if it replicates the error? That would help us narrow down where the issue is occurring.
