### ISSUE TITLE
Probably text swapping

### ISSUE THREAD

**Issue by sl45sms** [dequelabs/axe-core#3819]
Sorry if I guess wrong, but seems like fail and pass text are interchanged here:

https://github.com/dequelabs/axe-core/blob/123b83c00f0e770dd784ce72ab1fddddf4a4961e/locales/_template.json#L956

**Comment by straker** [comment]
Yep, that's intentional. Axe-core has a concept of a non-true check where the pass/fail messages are reversed. So the [blink rule](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/blink.json) fails if the element is on the screen (visible). So the check returns as true which is normally a passing check, but since the check is used as the `none` check for the rule, `true` means a failure. Thus the pass/fail messages are reversed.
