### ISSUE TITLE
Axe-core 4.5.2 not finding invalid ID value error for aria-describedby

### ISSUE THREAD

**Issue by dakahn** [dequelabs/axe-core#3852]
### Product

axe-core

### Product Version

4.5.2 (Chrome)

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
In Axe-core ruleset 4.4.2 the error `aria attribute must conform to valid values` would be thrown when a control's `aria-describedby` value was invalid.
![image](https://user-images.githubusercontent.com/40970507/211683461-cb040b50-9c6c-414f-b24f-e1d2dccfc5b1.png)

#### Actual
In ruleset 4.5 (latest in Chrome) this error is not thrown--even thought `aria-describedby` points to the id of a non existent elemet.

#### How to Reproduce
1. on [heb.com](https://www.heb.com/) in the top right click Log in
2. on the Log in screen run Axe dev tools using ruleset 4.4
3. observe the error `aria attribute must conform to valid values`
4. change axe dev tools ruleset to 4.5
5. observe there is no error even though invalid id remains

#### Additional context
Any thing else we should know about the issue?

**Comment by straker** [comment]
The devtools extension recently [disabled Needs Review items from showing in the results panel](https://docs.deque.com/devtools-html/4.0.0/en/devtools-4-46-2). This is the reason why the issue is no longer showing up (it was an Incomplete / Needs Review item since the id does not exist on the page).
