### ISSUE TITLE
[axe-extension] Dom error when insert a iframe

### ISSUE THREAD

**Issue by woody-li** [dequelabs/axe-core#4254]
### Product

axe-core

### Product Version

4.8.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
No errors.

#### Actual
Console error:
> Uncaught TypeError: Cannot read properties of undefined (reading 'appendChild')

at:
> document.getElementsByTagName("head")[0].appendChild(ee)

The element quey result is a empty list, so the index 0 is undefined.

#### How to Reproduce
* Open a site, such as https://www.google.com/
* Execute the script:
```javascript
var frame = document.createElement('iframe');
frame.setAttribute("sandbox", "");
document.body.append(frame);
```

#### Additional context
Chrome: 119.0.6045.160 (Official Build) (64-bit)
axe Extension: 4.68.1

**Comment by straker** [comment]
Thanks for the issue. I've let the appropriate team know.

**Comment by thuey** [comment]
Hi @woody-li.

Thanks for reporting this issue. The error message you are seeing should be benign. It's caused because some code in a 3rd-party dependency assumes there is a `<head>` element, but there's not one in the iframe you injected to the page. Aside from the error message itself, it shouldn't cause any problems.

Are there any problems you are noticing other than the error message?

**Comment by woody-li** [comment]
Yeah, it doesn't metter about any feature.
Only error log message.

**Comment by thuey** [comment]
@woody-li 

After investigating this more, it looks like that 3rd-party dependency shouldn't be included in this scenario you described. I'm re-opening the ticket. We'll work to get it addressed.

**Comment by Amandeque** [comment]
This issue was [fixed](https://github.com/dequelabs/axe-extension/issues/4314) in Axe Devtools Extension v4.73.0 release, so I am closing this ticket.
