### ISSUE TITLE
`listbox` role is not a valid role for `<select>` in `aria-allowed-role` check

### ISSUE THREAD

**Issue by adamraine** [dequelabs/axe-core#4256]
### Product

axe-core

### Product Version

4.8.1

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation

`listbox` is recognized as a valid role for `<select>` element.

#### Actual

`listbox` is not recognized as a valid role for `<select>` element.

#### How to Reproduce

Run axe-core on the following page: https://www.eventbrite.com/checkout-external?eid=695245567207&alias=add-ons-event

#### Additional context
https://github.com/GoogleChrome/lighthouse/issues/15630

**Comment by straker** [comment]
Thanks for the issue. According to ARIA in HTML (which defines which ARIA roles and attributes are allowed on elements) the `select` element is only allowed the `listbox` role when [it has the attribute `multiple` or `size` > 1](https://www.w3.org/TR/html-aria/#el-select-multiple-or-size-greater-1). Otherwise the [only allowed roles are `menu` or `combobox`](https://www.w3.org/TR/html-aria/#el-select).

**Comment by adamraine** [comment]
Thanks @straker!
