### ISSUE TITLE
"group-labelledby" check to use the composed tree

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#426]
"group-labelledby" check to use the composed tree

**Comment by marcysutton** [comment]
What if the same input name is referenced across the shadow boundary? Should we flag it since you can't use the same label idRef like we do in the other tests? Not sure how common that would be, but I was wondering what uses cases to test for.

**Comment by WilcoFiers** [comment]
Do you mean that the labelledby points to different elements, but that those elements have the same accessible text? I guess that makes sense. Have a look at what happens when input elements with the same name exist in different shadow trees. Does the browser still consider them part of the same group? I'd suggest that only if it does, should we look to match names instead of just element references. WDYT?

**Comment by marcysutton** [comment]
The `name` grouping does not work across the boundary–radios aren't grouped together . So I don't think that's a valid use case. The test scenarios I think this should cover are:

- Return false if the label referenced is outside of the boundary
- Return true if the label is inside of the boundary
- Return false if the inputs are spread across the boundary (because it doesn't work)

**Comment by marcysutton** [comment]
Closed with #458.
