### ISSUE TITLE
label-content-name-mismatch how long until out of experimental? 

### ISSUE THREAD

**Issue by joe-watkins** [dequelabs/axe-core#4324]
### Product

axe-core

### Question

Hello AxeCore team! Google Lighthouse has removed the test `label-content-name-mismatch` because it is in an experimental status. This test is much needed as issues it can help identify are common offenders for accessibility barriers.

Is there a rough idea of when that could come out of "experimental" so tools could safely utilize it? 

https://github.com/GoogleChrome/lighthouse/issues/15519
https://dequeuniversity.com/rules/axe/4.8/label-content-name-mismatch?application=RuleDescription
https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md#experimental-rules

**Comment by WilcoFiers** [comment]
Hey Joe, unfortunately at this moment the rule still has various false positives in it that would need to be resolved first. We currently have no plans for working on it. The value of this rule is also somewhat in question, since most voice assistive tech allows controlling elements by its visible text.

This particular WCAG criteria is much more important for images of text than it is for real texts, and those are not something axe-core can test.

**Comment by joe-watkins** [comment]
Tnx @WilcoFiers ! :) 

> The value of this rule is also somewhat in question, since most voice assistive tech allows controlling elements by its visible text.

Some things that could impact the value question:

- I wish Apple's Voice Control was as forgiving as Dragon on this. If that visual label is not in the name, Apple voice users have to fallback to other mechanisms for interaction (show numbers, mousegrid). 
- There are also sighted screen reader user benefits from the visual label being part of the accessible name for a control. 
- Other automated tools used by potential litigants could have a different stance on this test than yours / [ACT Rule](https://act-rules.github.io/rules/2ee8b8) and actually perform the test. If I rely on Axe coverage as an automated testing solution for my business, am I exposed to risk as a result?

+1 for considering the work to get another testable thing into the wild and out of experimental.
