### ISSUE TITLE
Axe is not identifying the color contrast issue when text is in white color with white background

### ISSUE THREAD

**Issue by Yoginath458** [dequelabs/axe-core#4327]
### Product

axe-core

### Product Version

axe-core 4.8.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
When text is in white color with white background then axe tool should go through color contrast issue

#### Actual
When text is in white color with a white background then the axe tool should not be identifying the color contrast issue

#### How to Reproduce
Change the text color and background color to white and run the axe extension 

#### Additional context
Provided color code :#FFFFFF
![image](https://github.com/dequelabs/axe-core/assets/159112445/8d1f35ca-7d88-4f6c-851f-c9aa8ed1a275)

**Comment by straker** [comment]
Thanks for the issue. This is expected behavior as making the foreground the same color as the background is a technique to visually hide text while still allowing screen reader users to access it. We report these elements as Needs Review items (`incomplete`) so they can be checked to make sure they are really an accessibility problem or not. In the extension these are hidden by default, but you can enable [Needs Review items in the options](https://docs.deque.com/devtools-html/4.0.0/en/devtools-configuration#rules-and-issues).
