### ISSUE TITLE
The color of visited links isn't assessed

### ISSUE THREAD

**Issue by fstrr** [dequelabs/axe-core#4337]
### Product

axe Extension

### Product Version

4.8.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Note: this might be related to the [privacy restrictions on the :visited state](https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector), but I'm not sure so here's an issue in case it is a valid bug.

On a recent audit, a link had a non-conforming color ratio but its :visited state ratio was good. I noticed that axe dev tools ignored the :visited state's color on one link and, instead, reported its default / non-visited color. My expectation is that axe dev tools would not flag the conforming visited link as it had sufficient contrast.

#### Actual
Axe dev tools doesn't use the visited state's color. It uses the link's default color instead.

#### How to Reproduce
[CodePen with links and instructions](https://cdpn.io/pen/debug/ExMzqwP).

**Comment by straker** [comment]
Thanks for the issue. As you've correctly pointed out, axe-core has no way to access the link color of visited links due to privacy concerns, so wouldn't be able to make a decision about using the visited color over the non-visited color when performing color-contrast. Since the extension uses axe-core and we especially want results to be consistent between the extension and the APIs (meaning running both under the same setup would produce the same results), we wouldn't want to implement an extension only rule / change that would then give different results.

With that in mind, I'm going to close this issue as not planned. Thanks again for the suggestion.
