### ISSUE TITLE
Should <input> elements within gridcells require a label?

### ISSUE THREAD

**Issue by turjmner8** [dequelabs/axe-core#4367]
### Product

axe-core

### Question

I'm using axe-core 4.7 on a data grid implementation of role='grid', and am working to implement a roughly 'excel-like' editing structure where most cells in the grid contain a single input of type='text' that take up the full cell. In most cases, I have some cells with data already entered that are marked as 'rowheader', but in all cases there are also 'columnheader' role cells for each column as well.

On the input elements themselves, adding an aria-label or aria-labelledby attribute doesn't make a ton of sense on its own as there really isn't a label other than the row or column header (really the combination of the 2 of them), but setting the column header or row header as the label on the input element causes that information to be read out multiple times by the screen readers I have tested with. Leaving both of those values out seems to be a critical issue flagged by axe-core though, so I am not really sure what the expectation for inputs in a 'gridcell' should be. Should there be an exception for children of 'grid' or possibly 'table' elements for labels on child inputs due to the nature of the cell structure and header cells already present, or does this seem like something that should still be present, and maybe bugs should be filed against screen readers to stop reading out the label a second time if its labelledby points to the 'columnheader' role element or something similar?

Axe-core errors I see when providing no label:

Ensures every form element has a label

[More info...](https://dequeuniversity.com/rules/axe/4.7/label?application=axeAPI)
#_dzuh5j4jbff-input

Critical Form element does not have an implicit (wrapped) <label>
Critical Form element does not have an explicit <label>
Serious aria-label attribute does not exist or is empty
Serious aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Serious Element has no title attribute
Serious Element has no placeholder attribute

The behavior I get in Jaws and NVDA is very similar here when navigating the grid, as the following type of information is read out when a label is present (column header only for simplicity):

'ROW [row number], [column header value], COLUMN [column number], [aria-label], EDIT [input value]'

So if I navigated to Row 2, Column 3, with a column header of 'Employee Name' and a value of 'Mike', I would hear the following:

Row 2, Employee Name, Column 3, **Employee Name**, edit Mike

Specifically that second reading out of the label in this case is the behavior I am trying to resolve without breaking the overall accessibility of the input elements within the grid.

Thanks for any help here!

**Comment by WilcoFiers** [comment]
@turjmner8 That's quite an interesting scenario. My gut reaction to it was that yes, these need an accessible name still. People navigate in different ways, including going between form fields. If you're navigating between form fields rather than navigating between grid still you're left without context.

On the other hand, the context is pretty easy to find, just go up to the current cell, the information is right there. You can do more or less the same with form fields and adjacent labels though, and those still require an accessible name. Screen readers are developed so that in forms mode they skip label elements because they should be announced when they hit the actual form field. But using aria-labelledby instead of native label elements is still allowed, and you could get duplicate information doing it that way.

So yeah, I'm a bit conflicted on this one. I'll ask around to hear what others have to say.


Separate from that question though I would suggest a different approach might work better. If this is an excel-like thing you may want to consider only ever having one input element on the screen, rather than putting one in every cell. In spreadsheet software (and most data grids too) you have to activate the cell to get to the edit. Activating one sell ends the edit of another. It should make navigating the grid easier, and you also don't end up putting hundreds of form fields in the screen reader's form fields list. That single field should then probably have the name of the grid, plus its row and column header/number in the name.

**Comment by turjmner8** [comment]
Thanks for the information here, and I'd definitely be interested to see what others have to say as well if you are able to follow up. I was seeing the double readouts regardless of aria-label vs aria-labelledby as well.

And I agree with your suggestion about not having all cells editable all the time. Depending on the customer, we will have something like 'enter' trigger editing to be enabled on that individual cell alone, or in some cases that cell's entire row. In other (hopefully smaller grids), some customers will insist on having all cells editable at all times, or potentially an empty top row editable at all times that is used for entering a new row for example.

For simplicity in terms of the correct acc markup, I was just trying to consider the case where a cell (or cells) have a single input within them at all times, and specifically for that state, what the expected requirements for labels would be (most of these complex scenarios end up having that input element paradigm rendered at some point within the grid and double readouts seem to occur in most if not all of them).

**Comment by WilcoFiers** [comment]
W3C has this example of it too: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/#ex2_label

I don't like how when you edit the input element has no name. I'll file an issue with them about it. That doesn't seem right. ARIA explicit requires an accessible name for that, so it's a bit odd that this one doesn't have it. But the rest is solid.

**Comment by WilcoFiers** [comment]
Closing this. I believe axe is doing the correct thing here.
