### ISSUE TITLE
autocomplete-valid (SC 1.3.5) triggers error for autocomplete="text"

### ISSUE THREAD

**Issue by cstrobbe** [dequelabs/axe-core#4492]
### Product

axe Extension

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
`autocomplete="text"` is not flagged as a violation of SC 1.3.5.

#### Actual
Axe Devtools flags `<input class="form-text" id="term" name="term" type="text" aria-required="false" autocomplete="text" placeholder="Zoek op titel, trefwoord" value="">` as a WCAG violation.

#### How to Reproduce
Create a page with something like `<input class="form-text" id="term" name="term" type="text" aria-required="false" autocomplete="text" value="">`  (basically a generic search field) or go to [Zoek een tool](https://www.mediawijs.be/nl/zoek-een-tool/zoeken). Run Axe Devtools and notice that it reports the following issue: [autocomplete attribute must be used correctly](https://dequeuniversity.com/rules/axe/4.9/autocomplete-valid). 

#### Additional context
While "text" is not among the [values listed in the HTML specificiation](https://html.spec.whatwg.org/#autofilling-form-controls:-the-autocomplete-attribute), the field does not collect information about the user, so SC 1.3.5 is not even applicable.

**Comment by WilcoFiers** [comment]
Thanks for reporting this @cstrobbe. I agree with you this doesn't fail WCAG. An autocomplete attribute that isn't needed doesn't need to be valid. We have a few other rules where we have harmless "common" HTML mistakes reported as needing review rather than as an issue. I think that's the way to go here. Looking into [GitHub search](https://github.com/search?q=autocomplete%3D%22text%22&type=code) it seems people do use `autocomplete="text"` from time to time.

**Comment by gaiety-deque** [comment]
Wilco suggested I add a list, that contains `text` for now. Bonus points if I add other common harmless mistakes.

If autocomplete is any in this list, `autocomplete` it.
