### ISSUE TITLE
 [role]s are not contained by their required parent element

### ISSUE THREAD

**Issue by crimsoniv0j** [dequelabs/axe-core#4554]
### Product

axe-core

### Question

Please help me to fix this.
<img width="557" alt="Screenshot 2024-08-06 224611" src="https://github.com/user-attachments/assets/529bca17-2a6f-4ead-be6d-89076bc6738f">
And this is my blog HTML
<img width="641" alt="Screenshot 2024-08-06 224659" src="https://github.com/user-attachments/assets/094bc4ae-43d7-4ed6-a5cf-c6a19f967f53">

**Comment by straker** [comment]
Thanks for the question. At first glance it would seem the issue is with the `<li>` that is in between the parent `ul[role=menubar]` element and the `a[role=menuitem]` element. The `<li>` will retain it's inherit role of `listitem` which is not allowed as a parent to a `menuitem`. You should be able to fix it by adding `role=none` to the `<li>`.

**Comment by crimsoniv0j** [comment]
> Thanks for the question. At first glance it would seem the issue is with the `<li>` that is in between the parent `ul[role=menubar]` element and the `a[role=menuitem]` element. The `<li>` will retain it's inherit role of `listitem` which is not allowed as a parent to a `menuitem`. You should be able to fix it by adding `role=none` to the `<li>`.

Thank you very much! Now, it's all good!
