### ISSUE TITLE
What is the best practice for videos with no audio?

### ISSUE THREAD

**Issue by adamraine** [dequelabs/axe-core#4638]
### Product

axe-core

### Question

https://github.com/GoogleChrome/lighthouse/issues/16244

In reference to [this axe rule](https://dequeuniversity.com/rules/axe/4.10/video-caption) about video captions.

The use case presented in this issue involves a `<video>` element which does not include any audio and is just there to show a QR code. Since there is no audio, should there still be captions for the video?

**Comment by Jeremy-Rivera** [comment]
I would presume that it wouldn't be 'required' to leave the captions off since there is no auditory information to convey. The principle is:

"The captions should convey **all meaningful auditory information** in the video including dialogue, musical cues, sound effects, and other relevant information for deaf users."
[https://dequeuniversity.com/rules/axe/4.10/video-caption]

Granted, it’s still **essential** to ensure the video content is accessible by providing a text alternative or a description that conveys the purpose of the video. This could be done by:
* Adding a text description nearby (e.g., “QR code for access”).
* Including a descriptive aria-label or alt text that mentions what the video displays.
[https://www.section508.gov/create/captions-transcripts/]

_example_:
```
<video width="300" height="200" aria-label="QR code for access">
    <source src="myVideo.mp4" type="video/mp4">
</video>
```

**Comment by adamraine** [comment]
Seems reasonable, does the axe-core rule allow for this? Would putting an `aria-label` on a video element be just as good as adding captions?

**Comment by WilcoFiers** [comment]
Axe-core does not fail videos without captions, although it reports them as needing manual review. Most videos do need captions, so when they don't have it, that is something something to look at.
