### ISSUE TITLE
discrepancies in the results obtained

### ISSUE THREAD

**Issue by douglascugliaridev** [dequelabs/axe-core#4649]
Good evening, I noticed discrepancies in the results obtained using Axe Core and Axe Core DevTools. Could this difference be related to the version of each application?

**Comment by WilcoFiers** [comment]
There are a lot of things that can result in difference when running axe in different ways. Different versions is one. Axe-core also has a different default ruleset then the axe extension does. Axe extension does not run best practices by default. It is also possible for the page to be in a different state. Often when running axe automatically we find the page isn't fully loaded yet, either because some elements only load after the page is scrolled, or the automated script didn't wait for everything to load in.

Hope that helps!

**Comment by douglascugliaridev** [comment]
Hello, I would like to know if I can do an analysis using the Axe-core to analyze only for example by the WCAG 2.1A and WCAG 2.1 AA tag. Pegunto, because I’m trying to do an analysis by just passing these two Tags and it’s not bringing any problem. Already in the Axe-Core Devtools Free version that comes with the WCAG 2.1 AA tag selected it brings several defects to the page I’m analyzing.
