### ISSUE TITLE
Ignore shadowRoots on elements that don't allow them

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#505]
Came across an issue of axe 3.0 not being able to build its tree correctly. Turned out it was caused by Chrome, which has recently added a shadow root to every HTML element. This tripped `axe.utils.flattenTree` up massively.

The solution is to only build the shadow tree for elements allowed to have shadow trees:
https://dom.spec.whatwg.org/#dom-element-attachshadow

Only valid custom element names, "article", "aside", "blockquote", "body", "div", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "main" "nav", "p", "section", or "span",

**Comment by marcysutton** [comment]
@robdodson do you know why Chrome 60 puts head and body into a shadow root? 
![Element inspection of HTML page with shadow root](https://user-images.githubusercontent.com/1045233/29884312-efd4512a-8d67-11e7-82c9-6a835c37fe6f.png)

**Comment by robdodson** [comment]
I'm not seeing this shadow root behavior in Chrome 60. It would surprise me if they did something like that to be honest.

![image](https://user-images.githubusercontent.com/1066253/30015699-bad44fe6-9106-11e7-90ba-bcfb9a2455ba.png)

Your example seems a little strange to me because it also seems to contain `<shadow>` tags, but that's not something I've ever seen before. Here's a screenshot inspecting the shadow dom on the polymer site.

![image](https://user-images.githubusercontent.com/1066253/30015735-eccb22d6-9106-11e7-9931-775c0ee312a2.png)

Are you maybe running an extension or perhaps your test harness is doing something weird?

**Comment by robdodson** [comment]
Oh interesting, can you tell me which one? I can reach out to the author if it's public

**Comment by WilcoFiers** [comment]
Yeah, it's AdBlocker https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom

I'm curious to know how they even attach a shadowTree to the root at all. As far as I can tell attachShadow() isn't able to do that. Are there other APIs we should consider with axe-core?

**Comment by robdodson** [comment]
oh I wonder if they're doing some weird Shadow DOM v0 stuff
https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-301/#toc-shadow-insertion

I'll have to go look at their source and try to figure out what's up...

Personally I wouldn't suggest investing a ton of energy in supporting Shadow DOM v0. It only ever shipped in Chrome and is deprecated.

**Comment by robdodson** [comment]
I pinged the AdBlock folks on twitter regarding this issue https://twitter.com/rob_dodson/status/937760083500351488
