### ISSUE TITLE
Automated testing on authenticated PHP pages?

### ISSUE THREAD

**Issue by Alioo** [dequelabs/axe-core#510]
A lot of our front end is still in PHP and so we use codeception for acceptance testing/functional testing. Is there a way that we can use codeception on phantomjs to check the accessibility with Axe. The problem I run into otherwise is that with the tests that just automate hitting a page, I am not sure how to handle pages that need authentication.

Thanks.

**Comment by marcysutton** [comment]
This isn't something axe-core itself would do–you'll have to get the page into the correct state in your tests before running the accessibility audit.

Common authentication examples I've seen use Selenium Webdriver to script the login and then run [axe-webdriverjs](https://github.com/dequelabs/axe-webdriverjs/). You could potentially do something similar with phantomjs ([settings documentation here](http://phantomjs.org/api/webpage/property/settings.html)), but that would be outside of the scope of axe-core since it doesn't call phantom itself. In axe-cli, perhaps, but that would be an issue for the [axe-cli project](https://github.com/dequelabs/axe-cli/).
