### ISSUE TITLE
axe version on rule description documentation

### ISSUE THREAD

**Issue by goetsu** [dequelabs/axe-core#591]
Hi, 

as axe is implemented in a vast eco system of tools and each tools may use a different version of axe core, is it possible to add on this file https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md for each rule what is the version of axe core from which they exist.

For example someone using sonarwhal that use axe core 2.4.4 will be able to know what rule is used in his case.

Another interesting features will be to have a link for each rule to the corresponding file (or part of code in a file) where the code of the corresponding rule is. This will allow to know what is really tested.

**Comment by WilcoFiers** [comment]
Hi @goetsu Thanks for the questions. We keep a changelog that I suggest you use to work out what rules where released when: https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md I think this is much better, since when a rule was introduced doesn't tell you about big changes that occurred either. The changelog has that sort of information too.

As for your second question. I'd consider it a bad sign if people have to look at the source code to figure out why something is a violation. We have the help URLs, which have extensive documentation about why something is a violation and how to resolve it. If you have specific instances where you feel this documentation is insufficient, please create separate tickets for this.

**Comment by goetsu** [comment]
@WilcoFiers using the changelog I only see two new rules between 1.0.1 and 2.4.2 that's it ?

For second question, my point was not about why something is a violation and how to resolve it. It's about having technical informations on what the test is doing exactly for example do the alt attribute test check image inside link ? or do it invalidate image without alt but role="presentation", etc. This while allow a quicker review of test rules and possible comments for improvements. Otherwise either we need to deep dive in the code to find that ourself or create lots of test case to check what pass or not

**Comment by WilcoFiers** [comment]
@goetsu That doesn't seem right. Off the top of my head I can come up with half a dozen new rules from 1.0 to 2.0. The focus for 2.0 wasn't on rule development though. For 3.x we're working on quite  a few more.

As for your second point, this is something we've only started doing pretty recently. As of axe 2.4 we're requiring new rules to have a technical description using the [aXe Rules format](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-proposal.md). We recognise the need for this type of documentation, which is why we are leading efforts at the W3C in developing a [format](https://www.w3.org/TR/act-rules-format/) that can be used by different accessibility test tools.

We intend to adopt the ACT Rules Format as soon as it has matured sufficiently. If at that point we'll be developing these documents for existing rules, or if we're simply going to build on top of this and use it as reference material isn't determined yet.

If you're interested in rule development, there is a W3C community group called [Auto-WCAG](https://www.w3.org/community/auto-wcag/) that we are also involved with which is working on test rules today. It is open to anyone, so you're more than welcome to join it if you are interested in this sort of thing.
