### ISSUE TITLE
Clarification on writing own rules

### ISSUE THREAD

**Issue by kahunacohen** [dequelabs/axe-core#653]
Hi what would be the use-case for registering a new custom rule vs writing a plugin? Let's say I want axe to perform an arbitrary check for something in the DOM, say adherence to an organizational style standard. Is this possible? What's the best way to do this?

**Comment by WilcoFiers** [comment]
All the information you need to develop custom rules for axe-core is in the developer guide. If you're using axe-core directly, that should have enough of what you need. Generally though, we don't recommend developing custom rules for axe-core. The problem with them is that, even though they work in axe-core, it's much harder to get custom rules working in all of the tools build on top of axe-core (axe-cli, axe-webdriverjs, the Chrome / Firefox extensions, etc.). If you're not using any of those, you should be good. But if you are, it's recommended you do one of the following:

1. Contribute your rules to axe-core as best-practice rules. This does mean meeting all the usual requirements. They have to be true best practices, without exception, and they can't have false positives. That will ensure they get released along with axe-core and they'll be available everywhere.
2. Use [WorldSpace Attest](https://www.deque.com/products/worldspace-attest/) instead. This product is designes to solve this problem (and more) for you. It's how we fund most of the work on axe-core.

I hope that helps. I'm closing the issue, since it's not directly related to bugs or feature requests. But please let us know if there's anything else we can help out with.
