### ISSUE TITLE
We need some criteria for deciding what should be a "needs review" rule

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#838]
Recent discussion on alt attributes with only punctuation has exposed missing guiding principles that can help with deciding when we implement a "needs review" rule.

I propose the following guiding principles: a "needs review" rule should be implemented to expose situations that are not a 100% issue but meet one of the following conditions:

1) The automated rule hits a wall (example color contrast),
2) We have identified a suspicious situation, where, we have data that shows that there is a greater than 90% chance that the suspicious situation is an accessibility issue, or
3) The rule can significantly reduce the number of items on the page that need to be inspected (example: reading order)

**Comment by WilcoFiers** [comment]
I have a few conditionals to go with that:

1. Rules should not give a false sense of success
2. Rules should result in workable amounts of incomplete results (e.g. an average page should not give back 200+ review items)
3. Rules should be applicable to at least 0.1% of web pages, or be of critical severity

That first one is why we started tracking incomplete results in the first place. Because the color-contrast rule was giving people the incorrect impression that they passed all color contrast requirements. I think rules should flag **everything** in a particular problem category that needs to be reviewed, not just things that are suspicious, because that may lead people to think they don't need to do anything else. 

I think as far as #2 is concerned, our color-contrast rule breaks this right now, which is why I want to update it so it can test images and gradients.

Regarding my third point, unless something is critical, we shouldn't spend our time on rules that doesn't give us results.

**Comment by straker** [comment]
Wilco also mentioned that we should not implement best practice rules that only return needs review.

**Comment by WilcoFiers** [comment]
We're creating so few new rules these days I don't think it's useful for us to come up with criteria. The rule of thumb is that best practices should always be able to return failures; WCAG rules can on occasion return needs review, but only if the chance of a failure is high, and if that rule doesn't produce "noise"; i.e. flagging a things frequently.
