### ISSUE TITLE
Add support for shadowDOM

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#87]
Similar to what is in accessibility-developer-tools https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/js/AuditRule.js#L129

**Comment by felixzapata** [comment]
hi, any update about this issue? With the Chrome extension for a project demo built with Polymer, with Shadow DOM the extension says that there are no errors, but without Shadow DOM the extension can analyze the page.

I've used the API with the console too, and the results are the same.

![shadow-dom](https://cloud.githubusercontent.com/assets/997038/18984845/2b58b4e0-86f5-11e6-9515-b44dda48fbea.png)

![no-shadow-dom](https://cloud.githubusercontent.com/assets/997038/18984851/351ef82c-86f5-11e6-9b10-b5f222591d68.png)

**Comment by marcysutton** [comment]
@dylanb I think the original Chrome A11y Developer Tools source changed, so it's unclear which part of the source was linked. 

We use document.querySelector methods which don't step into the Shadow DOM, right? Does the Chrome version do the work of iterating over nodes to audit instead of relying on DOM APIs? We might need something similar to support a subset of rules for testing virtual DOM (using JSDOM, pre-compiled Angular 2, etc.).

**Comment by dylanb** [comment]
This work is backlogged. @marcysutton it is a lot more complex than just iterating into shadow roots. For example IDs can be unique within each shadow root. Also, trying to figure out what the computed styles are...

@felixzapata best short-term route is to use the polymer polyfilled DOM and ignore unique ID issues when the IDs live in their own shadow DOM

**Comment by seancurtis** [comment]
Could you check for a shadow root on each node (maybe just on custom elements) and then just test the markup within it in isolation of the rest of the page? They're supposed to be a new document context anyway. Maybe not all tests are needed (eg you could potentially ignore ID uniqueness).

**Comment by alice** [comment]
@seancurtis That would seem to be in the spirit of Shadow DOM, yeah.

**Comment by WilcoFiers** [comment]
The difficulty is in keeping this performant. It makes sense to limit Shadow DOM testing to custom elements. If anyone is interested in helping out building this into axe, I'd be happy to pitch in.

**Comment by alice** [comment]
On the performance issue, do you track performance already?

@ricksbrown did an amazing [refactor](https://github.com/GoogleChrome/accessibility-developer-tools/pull/265) of accessibility-developer-tools where he pulled the entire "gather" step into one single tree traversal, instead of doing a traverse or select (which does a more efficient traverse on the browser-side) for each rule. Would that be feasible for axe-core?

Short of that, how would you find custom elements in the page? Is there a way to do it without traversing? And, obviously, this wouldn't handle cases where developers have used Shadow DOM without using custom elements (see: Chrome DevTools for an example), but I guess that's enough of a corner case not to worry about?

**Comment by marcysutton** [comment]
Side-note: I'm working on performance right now as part of #240. That work should definitely help since we're using a style cache for lookups instead of traversing the tree over and over.

**Comment by TalhaAydin** [comment]
Hi all. When shadow dom support is released, how big do you expect the breaking changes to be to the current API and generated results object (if any)?

**Comment by marcysutton** [comment]
@TalhaAydin you can review the work being conducted in the shadowDOM branch: #317

**Comment by dylanb** [comment]
@TalhaAydin there will be no changes to the API when you use the library

There will be changes to the API that rules use, so if a rule uses commons or utils functions, it may have to be updated. Rules that do not use commons and util functions will continue to function as before

The results object will only change for violations that are found within shadowDOM. The `target` attribute of the `node` objects that are part of the `violations` and other arrays will be an array of either strings or array(s) of strings instead of just being an array of strings.

We will update the version number to because of these changes.

**Comment by marcysutton** [comment]
Closed with #317.
