### ISSUE TITLE
New Rule: Disallowed ARIA role for given element

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-core#97]
Some elements have a specific set of roles they can be given:

http://www.w3.org/html/wg/drafts/html/CR/dom.html#sec-strong-native-semantics

**Comment by marcysutton** [comment]
The link in that comment throws a 404. But I'm pretty sure we covered this with implicit roles.

**Comment by dylanb** [comment]
@marcysutton Here is the new link https://www.w3.org/TR/html5/dom.html#sec-strong-native-semantics you should check that we have it covered

**Comment by lemnis** [comment]
I was writing a function that calculates the role that should be used by the assistive technology. It contains the check mentioned above.

My code can be found at https://gist.github.com/lemnis/5f753515a34a8fc513bca6865c122330. It has some extra functionality but could be used as a starting point.  
It's based on a newer version than the one mentioned above, https://www.w3.org/TR/2017/WD-html-aria-20171013/#docconformance.

I would like to write the code for this rule, but I do not have any experience with the code base yet.

----

**Tags:** cat.aria, wcag411, wcag412, wcag2a

## Selector

`[role]`

## Checks

### elementHasAllowedRole ( any )

1. Get the role
2. Lookup if the given role is allowed with the element
3. Return false if the element doesn't support the given role
4. Otherwise, return true

**Comment by dylanb** [comment]
@lemnis thank you for your contribution but we cannot use that code unless you submit it as a pull request and accept the CLA

**Comment by WilcoFiers** [comment]
@lemnis Thanks for contributing! I think there are two things to talk about before reviewing the actual code you wrote. Firstly the rule ID. I think `aria-role-allowed` would fit better with what we've got currently. What do you think?

Secondly, have you done any testing with assistive technologies to see what they do with elements that have illegal roles on them? Are the roles ignored, or are they used? I didn't think browsers ever ignore the role attribute when building the accessibility tree. If that's the case, we should tag this as a `best practice` only.

**Comment by lemnis** [comment]
@WilcoFiers I think `aria-allowed-role` would be better, as there is already `aria-allowed-attr`. So it would keep the word order better in sync with existing roles.

I did a small test with Chrome and Safari in combination with force displaying a style and script tag with an added `role=button`. Both were happy to tell me it's a button. Nor did I hear that roles are ever ignored. Adding it as `best-practice` would be the best choice.

**Comment by WilcoFiers** [comment]
Works for me. Thanks Lisa!

**Comment by jkodu** [comment]
PR - https://github.com/dequelabs/axe-core/pull/945
