### ISSUE TITLE
Implement a standalone getSelector call

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#982]
A customer has asked for a standalone `getSelector` call - which would wrap all of this into a standalone API

```
/* setup */
axe._tree = axe.utils.getFlattenedTree(document.documentElement);
axe._selectorData = axe.utils.getSelectorData(axe._tree);
...
/* get selector(s) */
axe.utils.getSelector(target);
...
/* cleanup */
axe._tree = undefined;
axe._selectorData = undefined;
```

I propose implementing this as `axe.utils.getSingleSelector()` - any objections?

**Comment by WilcoFiers** [comment]
Do they need the same selector, or just any selector generator?  Because there are several of those on NPM already. We could even publish our 2.x solution to NPM. What you're proposing would be very slow - I don't think that meets our standard of quality TBH.

If they need an identical selector we could create a variation of this that works without the _selectorData. We'd just query for the selector data as we need it, rather than collect all of it up front and hope it is useful at some point. I'm not sure why that should live in core though. Seems like we could get more milage out of it as a separate module.

**Comment by dylanb** [comment]
@WilcoFiers does not need to be an identical selector, I would be ok with bringing back the 2.x selector generator

**Comment by marcysutton** [comment]
A note from the customer, they'd be fine with a separate npm package.

**Comment by WilcoFiers** [comment]
We've published a package called axe-selector on NPM. This uses the axe 2.x getSelector method.
